//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.16 at 09:04:14 AM PDT 
//


package org.pharmgkb.io.exporter.clinvar;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 *  MeasureTrait type is the assertion relationship stored in the
 *                 clinvar.measure_target table. This represents a single asserted relationship which
 *                 will be assigned an accession of the type SCV, RCV or NCV. 
 * 
 * <p>Java class for MeasureTraitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasureTraitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Assertion">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AssertionType">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;>typeAssertionType">
 *                           &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AssertionCriteriaFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ClinicalSignificance" type="{}ClinicalSignificanceType"/>
 *         &lt;element name="PathogenicityProperty" type="{}PathogenicityPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CustomAssertionScore" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CustomAssertionScoreType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExternalID" type="{}XrefType" minOccurs="0"/>
 *         &lt;element name="AttributeSet" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MeasureTraitAttributeType">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;>typeMeasureTraitAttributetype">
 *                           &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Attribute" type="{}AttributeType"/>
 *                   &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Severity" type="{}SeverityType" minOccurs="0"/>
 *         &lt;element name="ObservedIn" type="{}ObservationSet" maxOccurs="unbounded"/>
 *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}CVIdentifiers"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasureTraitType", propOrder = {
    "assertion",
    "clinicalSignificance",
    "pathogenicityProperty",
    "customAssertionScore",
    "externalID",
    "attributeSet",
    "severity",
    "observedIn",
    "xRef",
    "citation",
    "comment"
})
public class MeasureTraitType {

    @XmlElement(name = "Assertion", required = true)
    protected MeasureTraitType.Assertion assertion;
    @XmlElement(name = "ClinicalSignificance", required = true)
    protected ClinicalSignificanceType clinicalSignificance;
    @XmlElement(name = "PathogenicityProperty")
    @XmlSchemaType(name = "string")
    protected List<PathogenicityPropertyType> pathogenicityProperty;
    @XmlElement(name = "CustomAssertionScore")
    protected List<MeasureTraitType.CustomAssertionScore> customAssertionScore;
    @XmlElement(name = "ExternalID")
    protected XrefType externalID;
    @XmlElement(name = "AttributeSet")
    protected List<MeasureTraitType.AttributeSet> attributeSet;
    @XmlElement(name = "Severity")
    @XmlSchemaType(name = "string")
    protected SeverityType severity;
    @XmlElement(name = "ObservedIn", required = true)
    protected List<ObservationSet> observedIn;
    @XmlElement(name = "XRef")
    protected List<XrefType> xRef;
    @XmlElement(name = "Citation")
    protected List<CitationType> citation;
    @XmlElement(name = "Comment")
    protected List<CommentType> comment;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;
    @XmlAttribute(name = "ncbi_id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ncbiId;

    /**
     * Gets the value of the assertion property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureTraitType.Assertion }
     *     
     */
    public MeasureTraitType.Assertion getAssertion() {
        return assertion;
    }

    /**
     * Sets the value of the assertion property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureTraitType.Assertion }
     *     
     */
    public void setAssertion(MeasureTraitType.Assertion value) {
        this.assertion = value;
    }

    /**
     * Gets the value of the clinicalSignificance property.
     * 
     * @return
     *     possible object is
     *     {@link ClinicalSignificanceType }
     *     
     */
    public ClinicalSignificanceType getClinicalSignificance() {
        return clinicalSignificance;
    }

    /**
     * Sets the value of the clinicalSignificance property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClinicalSignificanceType }
     *     
     */
    public void setClinicalSignificance(ClinicalSignificanceType value) {
        this.clinicalSignificance = value;
    }

    /**
     * Gets the value of the pathogenicityProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pathogenicityProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPathogenicityProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PathogenicityPropertyType }
     * 
     * 
     */
    public List<PathogenicityPropertyType> getPathogenicityProperty() {
        if (pathogenicityProperty == null) {
            pathogenicityProperty = new ArrayList<PathogenicityPropertyType>();
        }
        return this.pathogenicityProperty;
    }

    /**
     * Gets the value of the customAssertionScore property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customAssertionScore property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomAssertionScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasureTraitType.CustomAssertionScore }
     * 
     * 
     */
    public List<MeasureTraitType.CustomAssertionScore> getCustomAssertionScore() {
        if (customAssertionScore == null) {
            customAssertionScore = new ArrayList<MeasureTraitType.CustomAssertionScore>();
        }
        return this.customAssertionScore;
    }

    /**
     * Gets the value of the externalID property.
     * 
     * @return
     *     possible object is
     *     {@link XrefType }
     *     
     */
    public XrefType getExternalID() {
        return externalID;
    }

    /**
     * Sets the value of the externalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link XrefType }
     *     
     */
    public void setExternalID(XrefType value) {
        this.externalID = value;
    }

    /**
     * Gets the value of the attributeSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasureTraitType.AttributeSet }
     * 
     * 
     */
    public List<MeasureTraitType.AttributeSet> getAttributeSet() {
        if (attributeSet == null) {
            attributeSet = new ArrayList<MeasureTraitType.AttributeSet>();
        }
        return this.attributeSet;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link SeverityType }
     *     
     */
    public SeverityType getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeverityType }
     *     
     */
    public void setSeverity(SeverityType value) {
        this.severity = value;
    }

    /**
     * Gets the value of the observedIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the observedIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObservedIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObservationSet }
     * 
     * 
     */
    public List<ObservationSet> getObservedIn() {
        if (observedIn == null) {
            observedIn = new ArrayList<ObservationSet>();
        }
        return this.observedIn;
    }

    /**
     * Gets the value of the xRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XrefType }
     * 
     * 
     */
    public List<XrefType> getXRef() {
        if (xRef == null) {
            xRef = new ArrayList<XrefType>();
        }
        return this.xRef;
    }

    /**
     * Gets the value of the citation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CitationType }
     * 
     * 
     */
    public List<CitationType> getCitation() {
        if (citation == null) {
            citation = new ArrayList<CitationType>();
        }
        return this.citation;
    }

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommentType }
     * 
     * 
     */
    public List<CommentType> getComment() {
        if (comment == null) {
            comment = new ArrayList<CommentType>();
        }
        return this.comment;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the ncbiId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNcbiId() {
        return ncbiId;
    }

    /**
     * Sets the value of the ncbiId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNcbiId(BigInteger value) {
        this.ncbiId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AssertionType">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;>typeAssertionType">
     *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AssertionCriteriaFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "assertionType",
        "assertionCriteriaFile",
        "xRef",
        "citation"
    })
    public static class Assertion {

        @XmlElement(name = "AssertionType", required = true)
        protected MeasureTraitType.Assertion.AssertionType assertionType;
        @XmlElement(name = "AssertionCriteriaFile")
        protected String assertionCriteriaFile;
        @XmlElement(name = "XRef")
        protected List<XrefType> xRef;
        @XmlElement(name = "Citation")
        protected List<CitationType> citation;

        /**
         * Gets the value of the assertionType property.
         * 
         * @return
         *     possible object is
         *     {@link MeasureTraitType.Assertion.AssertionType }
         *     
         */
        public MeasureTraitType.Assertion.AssertionType getAssertionType() {
            return assertionType;
        }

        /**
         * Sets the value of the assertionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link MeasureTraitType.Assertion.AssertionType }
         *     
         */
        public void setAssertionType(MeasureTraitType.Assertion.AssertionType value) {
            this.assertionType = value;
        }

        /**
         * Gets the value of the assertionCriteriaFile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssertionCriteriaFile() {
            return assertionCriteriaFile;
        }

        /**
         * Sets the value of the assertionCriteriaFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssertionCriteriaFile(String value) {
            this.assertionCriteriaFile = value;
        }

        /**
         * Gets the value of the xRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the xRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getXRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XrefType }
         * 
         * 
         */
        public List<XrefType> getXRef() {
            if (xRef == null) {
                xRef = new ArrayList<XrefType>();
            }
            return this.xRef;
        }

        /**
         * Gets the value of the citation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the citation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCitation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CitationType }
         * 
         * 
         */
        public List<CitationType> getCitation() {
            if (citation == null) {
                citation = new ArrayList<CitationType>();
            }
            return this.citation;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;>typeAssertionType">
         *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class AssertionType {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "val_type", required = true)
            protected TypeIdName valType;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the valType property.
             * 
             * @return
             *     possible object is
             *     {@link TypeIdName }
             *     
             */
            public TypeIdName getValType() {
                return valType;
            }

            /**
             * Sets the value of the valType property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeIdName }
             *     
             */
            public void setValType(TypeIdName value) {
                this.valType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MeasureTraitAttributeType">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;>typeMeasureTraitAttributetype">
     *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Attribute" type="{}AttributeType"/>
     *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "measureTraitAttributeType",
        "attribute",
        "citation",
        "xRef",
        "comment"
    })
    public static class AttributeSet {

        @XmlElement(name = "MeasureTraitAttributeType", required = true)
        protected MeasureTraitType.AttributeSet.MeasureTraitAttributeType measureTraitAttributeType;
        @XmlElement(name = "Attribute", required = true)
        protected AttributeType attribute;
        @XmlElement(name = "Citation")
        protected List<CitationType> citation;
        @XmlElement(name = "XRef")
        protected List<XrefType> xRef;
        @XmlElement(name = "Comment")
        protected List<CommentType> comment;

        /**
         * Gets the value of the measureTraitAttributeType property.
         * 
         * @return
         *     possible object is
         *     {@link MeasureTraitType.AttributeSet.MeasureTraitAttributeType }
         *     
         */
        public MeasureTraitType.AttributeSet.MeasureTraitAttributeType getMeasureTraitAttributeType() {
            return measureTraitAttributeType;
        }

        /**
         * Sets the value of the measureTraitAttributeType property.
         * 
         * @param value
         *     allowed object is
         *     {@link MeasureTraitType.AttributeSet.MeasureTraitAttributeType }
         *     
         */
        public void setMeasureTraitAttributeType(MeasureTraitType.AttributeSet.MeasureTraitAttributeType value) {
            this.measureTraitAttributeType = value;
        }

        /**
         * Gets the value of the attribute property.
         * 
         * @return
         *     possible object is
         *     {@link AttributeType }
         *     
         */
        public AttributeType getAttribute() {
            return attribute;
        }

        /**
         * Sets the value of the attribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link AttributeType }
         *     
         */
        public void setAttribute(AttributeType value) {
            this.attribute = value;
        }

        /**
         * Gets the value of the citation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the citation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCitation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CitationType }
         * 
         * 
         */
        public List<CitationType> getCitation() {
            if (citation == null) {
                citation = new ArrayList<CitationType>();
            }
            return this.citation;
        }

        /**
         * Gets the value of the xRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the xRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getXRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XrefType }
         * 
         * 
         */
        public List<XrefType> getXRef() {
            if (xRef == null) {
                xRef = new ArrayList<XrefType>();
            }
            return this.xRef;
        }

        /**
         * Gets the value of the comment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CommentType }
         * 
         * 
         */
        public List<CommentType> getComment() {
            if (comment == null) {
                comment = new ArrayList<CommentType>();
            }
            return this.comment;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;>typeMeasureTraitAttributetype">
         *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class MeasureTraitAttributeType {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "val_type", required = true)
            protected TypeIdName valType;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the valType property.
             * 
             * @return
             *     possible object is
             *     {@link TypeIdName }
             *     
             */
            public TypeIdName getValType() {
                return valType;
            }

            /**
             * Sets the value of the valType property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeIdName }
             *     
             */
            public void setValType(TypeIdName value) {
                this.valType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CustomAssertionScoreType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customAssertionScoreType",
        "xRef",
        "citation"
    })
    public static class CustomAssertionScore {

        @XmlElement(name = "CustomAssertionScoreType", required = true)
        protected String customAssertionScoreType;
        @XmlElement(name = "XRef")
        protected List<XrefType> xRef;
        @XmlElement(name = "Citation")
        protected List<CitationType> citation;
        @XmlAttribute(name = "Value")
        protected String value;

        /**
         * Gets the value of the customAssertionScoreType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomAssertionScoreType() {
            return customAssertionScoreType;
        }

        /**
         * Sets the value of the customAssertionScoreType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomAssertionScoreType(String value) {
            this.customAssertionScoreType = value;
        }

        /**
         * Gets the value of the xRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the xRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getXRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XrefType }
         * 
         * 
         */
        public List<XrefType> getXRef() {
            if (xRef == null) {
                xRef = new ArrayList<XrefType>();
            }
            return this.xRef;
        }

        /**
         * Gets the value of the citation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the citation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCitation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CitationType }
         * 
         * 
         */
        public List<CitationType> getCitation() {
            if (citation == null) {
                citation = new ArrayList<CitationType>();
            }
            return this.citation;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
