//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.16 at 09:04:14 AM PDT 
//


package org.pharmgkb.io.exporter.clinvar;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * This is an AttributeSet, there will be 1 attribute supported by
 *                 optional citations, xrefs and comment.                  There must be at least one
 *                 ObservedData Set, but can be any number.                 For each ObservedData set
 *                 the Attribute will be either decimal or string depending on type.
 *                 The value will be stored here, but decimals will be entered to the database as a
 *                 string.             
 * 
 * <p>Java class for ObservedDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObservedDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="ObsAttributeType">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;>typeObsAttributetype">
 *                   &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="ObsDecAttributeType">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;>typeObsdecAttributetype">
 *                   &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="Attribute" type="{}AttributeType"/>
 *         &lt;element name="Zygosity" type="{}ZygosityType" minOccurs="0"/>
 *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}CVIdentifiers"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObservedDataType", propOrder = {
    "obsAttributeType",
    "obsDecAttributeType",
    "attribute",
    "zygosity",
    "xRef",
    "citation",
    "comment"
})
public class ObservedDataType {

    @XmlElement(name = "ObsAttributeType")
    protected ObservedDataType.ObsAttributeType obsAttributeType;
    @XmlElement(name = "ObsDecAttributeType")
    protected ObservedDataType.ObsDecAttributeType obsDecAttributeType;
    @XmlElement(name = "Attribute", required = true)
    protected AttributeType attribute;
    @XmlElement(name = "Zygosity")
    @XmlSchemaType(name = "string")
    protected ZygosityType zygosity;
    @XmlElement(name = "XRef")
    protected List<XrefType> xRef;
    @XmlElement(name = "Citation")
    protected List<CitationType> citation;
    @XmlElement(name = "Comment")
    protected List<CommentType> comment;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;
    @XmlAttribute(name = "ncbi_id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ncbiId;

    /**
     * Gets the value of the obsAttributeType property.
     * 
     * @return
     *     possible object is
     *     {@link ObservedDataType.ObsAttributeType }
     *     
     */
    public ObservedDataType.ObsAttributeType getObsAttributeType() {
        return obsAttributeType;
    }

    /**
     * Sets the value of the obsAttributeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservedDataType.ObsAttributeType }
     *     
     */
    public void setObsAttributeType(ObservedDataType.ObsAttributeType value) {
        this.obsAttributeType = value;
    }

    /**
     * Gets the value of the obsDecAttributeType property.
     * 
     * @return
     *     possible object is
     *     {@link ObservedDataType.ObsDecAttributeType }
     *     
     */
    public ObservedDataType.ObsDecAttributeType getObsDecAttributeType() {
        return obsDecAttributeType;
    }

    /**
     * Sets the value of the obsDecAttributeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservedDataType.ObsDecAttributeType }
     *     
     */
    public void setObsDecAttributeType(ObservedDataType.ObsDecAttributeType value) {
        this.obsDecAttributeType = value;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeType }
     *     
     */
    public AttributeType getAttribute() {
        return attribute;
    }

    /**
     * Sets the value of the attribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeType }
     *     
     */
    public void setAttribute(AttributeType value) {
        this.attribute = value;
    }

    /**
     * Gets the value of the zygosity property.
     * 
     * @return
     *     possible object is
     *     {@link ZygosityType }
     *     
     */
    public ZygosityType getZygosity() {
        return zygosity;
    }

    /**
     * Sets the value of the zygosity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZygosityType }
     *     
     */
    public void setZygosity(ZygosityType value) {
        this.zygosity = value;
    }

    /**
     * Gets the value of the xRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XrefType }
     * 
     * 
     */
    public List<XrefType> getXRef() {
        if (xRef == null) {
            xRef = new ArrayList<XrefType>();
        }
        return this.xRef;
    }

    /**
     * Gets the value of the citation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CitationType }
     * 
     * 
     */
    public List<CitationType> getCitation() {
        if (citation == null) {
            citation = new ArrayList<CitationType>();
        }
        return this.citation;
    }

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommentType }
     * 
     * 
     */
    public List<CommentType> getComment() {
        if (comment == null) {
            comment = new ArrayList<CommentType>();
        }
        return this.comment;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the ncbiId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNcbiId() {
        return ncbiId;
    }

    /**
     * Sets the value of the ncbiId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNcbiId(BigInteger value) {
        this.ncbiId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>typeObsAttributetype">
     *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ObsAttributeType {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "val_type", required = true)
        protected TypeIdName valType;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the valType property.
         * 
         * @return
         *     possible object is
         *     {@link TypeIdName }
         *     
         */
        public TypeIdName getValType() {
            return valType;
        }

        /**
         * Sets the value of the valType property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeIdName }
         *     
         */
        public void setValType(TypeIdName value) {
            this.valType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>typeObsdecAttributetype">
     *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ObsDecAttributeType {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "val_type", required = true)
        protected TypeIdName valType;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the valType property.
         * 
         * @return
         *     possible object is
         *     {@link TypeIdName }
         *     
         */
        public TypeIdName getValType() {
            return valType;
        }

        /**
         * Sets the value of the valType property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeIdName }
         *     
         */
        public void setValType(TypeIdName value) {
            this.valType = value;
        }

    }

}
