//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.16 at 09:04:14 AM PDT 
//


package org.pharmgkb.io.exporter.clinvar;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PathogenicityPropertyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PathogenicityPropertyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="this variant, in a female, is causative"/>
 *     &lt;enumeration value="this variant, in a male, is causative"/>
 *     &lt;enumeration value="this variant is causative"/>
 *     &lt;enumeration value="this variant, when inherited from the father, is causative"/>
 *     &lt;enumeration value="this variant, when inherited from the mother, is causative"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PathogenicityPropertyType")
@XmlEnum
public enum PathogenicityPropertyType {

    @XmlEnumValue("this variant, in a female, is causative")
    THIS_VARIANT_IN_A_FEMALE_IS_CAUSATIVE("this variant, in a female, is causative"),
    @XmlEnumValue("this variant, in a male, is causative")
    THIS_VARIANT_IN_A_MALE_IS_CAUSATIVE("this variant, in a male, is causative"),
    @XmlEnumValue("this variant is causative")
    THIS_VARIANT_IS_CAUSATIVE("this variant is causative"),
    @XmlEnumValue("this variant, when inherited from the father, is causative")
    THIS_VARIANT_WHEN_INHERITED_FROM_THE_FATHER_IS_CAUSATIVE("this variant, when inherited from the father, is causative"),
    @XmlEnumValue("this variant, when inherited from the mother, is causative")
    THIS_VARIANT_WHEN_INHERITED_FROM_THE_MOTHER_IS_CAUSATIVE("this variant, when inherited from the mother, is causative");
    private final String value;

    PathogenicityPropertyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PathogenicityPropertyType fromValue(String v) {
        for (PathogenicityPropertyType c: PathogenicityPropertyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
