//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.16 at 09:04:14 AM PDT 
//


package org.pharmgkb.io.exporter.clinvar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * This is used to identify the one individual or process that is the
 *                 submitter of record,                 in contrast to the many who contributed to the
 *                 submission. The latter are reported under submitter.             
 * 
 * <p>Java class for SubmitterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubmitterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Person">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="First" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Last" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Middle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SubmitterHandle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AccountInfo" type="{}typeAccount"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="PersonID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Organization">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Institution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Department" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="SubmitterHandle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="OrganizationCategory" type="{}OrganizationCategoryList"/>
 *                   &lt;element name="NCBIOrganizationID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmitterType", propOrder = {
    "person",
    "organization"
})
public class SubmitterType {

    @XmlElement(name = "Person", required = true)
    protected SubmitterType.Person person;
    @XmlElement(name = "Organization", required = true)
    protected SubmitterType.Organization organization;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitterType.Person }
     *     
     */
    public SubmitterType.Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitterType.Person }
     *     
     */
    public void setPerson(SubmitterType.Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitterType.Organization }
     *     
     */
    public SubmitterType.Organization getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitterType.Organization }
     *     
     */
    public void setOrganization(SubmitterType.Organization value) {
        this.organization = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Institution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Department" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="SubmitterHandle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="OrganizationCategory" type="{}OrganizationCategoryList"/>
     *         &lt;element name="NCBIOrganizationID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "institution",
        "department",
        "submitterHandle",
        "organizationCategory",
        "ncbiOrganizationID"
    })
    public static class Organization {

        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "Institution")
        protected String institution;
        @XmlElement(name = "Department")
        protected String department;
        @XmlElement(name = "SubmitterHandle")
        protected String submitterHandle;
        @XmlElement(name = "OrganizationCategory", required = true, defaultValue = "lab")
        @XmlSchemaType(name = "string")
        protected OrganizationCategoryList organizationCategory;
        @XmlElement(name = "NCBIOrganizationID")
        protected Integer ncbiOrganizationID;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the institution property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInstitution() {
            return institution;
        }

        /**
         * Sets the value of the institution property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInstitution(String value) {
            this.institution = value;
        }

        /**
         * Gets the value of the department property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepartment() {
            return department;
        }

        /**
         * Sets the value of the department property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepartment(String value) {
            this.department = value;
        }

        /**
         * Gets the value of the submitterHandle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubmitterHandle() {
            return submitterHandle;
        }

        /**
         * Sets the value of the submitterHandle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubmitterHandle(String value) {
            this.submitterHandle = value;
        }

        /**
         * Gets the value of the organizationCategory property.
         * 
         * @return
         *     possible object is
         *     {@link OrganizationCategoryList }
         *     
         */
        public OrganizationCategoryList getOrganizationCategory() {
            return organizationCategory;
        }

        /**
         * Sets the value of the organizationCategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrganizationCategoryList }
         *     
         */
        public void setOrganizationCategory(OrganizationCategoryList value) {
            this.organizationCategory = value;
        }

        /**
         * Gets the value of the ncbiOrganizationID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNCBIOrganizationID() {
            return ncbiOrganizationID;
        }

        /**
         * Sets the value of the ncbiOrganizationID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNCBIOrganizationID(Integer value) {
            this.ncbiOrganizationID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="First" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Last" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Middle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SubmitterHandle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AccountInfo" type="{}typeAccount"/>
     *       &lt;/sequence>
     *       &lt;attribute name="PersonID" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "submitterHandle",
        "accountInfo"
    })
    public static class Person {

        @XmlElement(name = "Name", required = true)
        protected SubmitterType.Person.Name name;
        @XmlElement(name = "SubmitterHandle")
        protected String submitterHandle;
        @XmlElement(name = "AccountInfo", required = true)
        protected TypeAccount accountInfo;
        @XmlAttribute(name = "PersonID")
        protected Integer personID;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link SubmitterType.Person.Name }
         *     
         */
        public SubmitterType.Person.Name getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubmitterType.Person.Name }
         *     
         */
        public void setName(SubmitterType.Person.Name value) {
            this.name = value;
        }

        /**
         * Gets the value of the submitterHandle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubmitterHandle() {
            return submitterHandle;
        }

        /**
         * Sets the value of the submitterHandle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubmitterHandle(String value) {
            this.submitterHandle = value;
        }

        /**
         * Gets the value of the accountInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TypeAccount }
         *     
         */
        public TypeAccount getAccountInfo() {
            return accountInfo;
        }

        /**
         * Sets the value of the accountInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeAccount }
         *     
         */
        public void setAccountInfo(TypeAccount value) {
            this.accountInfo = value;
        }

        /**
         * Gets the value of the personID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPersonID() {
            return personID;
        }

        /**
         * Sets the value of the personID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPersonID(Integer value) {
            this.personID = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="First" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Last" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Middle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "first",
            "last",
            "middle",
            "suffix"
        })
        public static class Name {

            @XmlElement(name = "First", required = true)
            protected String first;
            @XmlElement(name = "Last", required = true)
            protected String last;
            @XmlElement(name = "Middle")
            protected String middle;
            @XmlElement(name = "Suffix")
            protected String suffix;

            /**
             * Gets the value of the first property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFirst() {
                return first;
            }

            /**
             * Sets the value of the first property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFirst(String value) {
                this.first = value;
            }

            /**
             * Gets the value of the last property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLast() {
                return last;
            }

            /**
             * Sets the value of the last property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLast(String value) {
                this.last = value;
            }

            /**
             * Gets the value of the middle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMiddle() {
                return middle;
            }

            /**
             * Sets the value of the middle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMiddle(String value) {
                this.middle = value;
            }

            /**
             * Gets the value of the suffix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSuffix() {
                return suffix;
            }

            /**
             * Sets the value of the suffix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSuffix(String value) {
                this.suffix = value;
            }

        }

    }

}
