//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.16 at 09:04:14 AM PDT 
//


package org.pharmgkb.io.exporter.clinvar;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TitleList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TitleList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Lab Director"/>
 *     &lt;enumeration value="Lab Associate Director"/>
 *     &lt;enumeration value="Medical Director"/>
 *     &lt;enumeration value="Genetic Counselor"/>
 *     &lt;enumeration value="Nurse"/>
 *     &lt;enumeration value="Research Nurse"/>
 *     &lt;enumeration value="Administrator"/>
 *     &lt;enumeration value="Staff"/>
 *     &lt;enumeration value="Principal Investigator"/>
 *     &lt;enumeration value="Contact"/>
 *     &lt;enumeration value="Informatics staff"/>
 *     &lt;enumeration value="CEO"/>
 *     &lt;enumeration value="Coordinator"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TitleList")
@XmlEnum
public enum TitleList {

    @XmlEnumValue("Lab Director")
    LAB_DIRECTOR("Lab Director"),
    @XmlEnumValue("Lab Associate Director")
    LAB_ASSOCIATE_DIRECTOR("Lab Associate Director"),
    @XmlEnumValue("Medical Director")
    MEDICAL_DIRECTOR("Medical Director"),
    @XmlEnumValue("Genetic Counselor")
    GENETIC_COUNSELOR("Genetic Counselor"),
    @XmlEnumValue("Nurse")
    NURSE("Nurse"),
    @XmlEnumValue("Research Nurse")
    RESEARCH_NURSE("Research Nurse"),
    @XmlEnumValue("Administrator")
    ADMINISTRATOR("Administrator"),
    @XmlEnumValue("Staff")
    STAFF("Staff"),
    @XmlEnumValue("Principal Investigator")
    PRINCIPAL_INVESTIGATOR("Principal Investigator"),
    @XmlEnumValue("Contact")
    CONTACT("Contact"),
    @XmlEnumValue("Informatics staff")
    INFORMATICS_STAFF("Informatics staff"),
    CEO("CEO"),
    @XmlEnumValue("Coordinator")
    COORDINATOR("Coordinator");
    private final String value;

    TitleList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TitleList fromValue(String v) {
        for (TitleList c: TitleList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
