//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssertionType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssertionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="variation to disease"/>
 *     &lt;enumeration value="variation to included disease"/>
 *     &lt;enumeration value="variation in modifier gene to disease"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "AssertionType")
@XmlEnum
public enum AssertionType {

    @XmlEnumValue("variation to disease")
    VARIATION_TO_DISEASE("variation to disease"),
    @XmlEnumValue("variation to included disease")
    VARIATION_TO_INCLUDED_DISEASE("variation to included disease"),
    @XmlEnumValue("variation in modifier gene to disease")
    VARIATION_IN_MODIFIER_GENE_TO_DISEASE("variation in modifier gene to disease");
    private final String value;

    AssertionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AssertionType fromValue(String v) {
        for (AssertionType c: AssertionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
