//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * The attribute is a general element to represent a defined set of data
 *                 qualified by an enumerated set of types. For each decimal attribute element, the
 *                 value will be a decimal and is optional. Source shall be used to store identifiers
 *                 for supplied data from source other than the submitter (e.g. SequenceOntology). This
 *                 is a generic version for decimal attributes and should be used with extension when
 *                 it is used to specify Type and its enumerations. The integerValue attribute type is
 *                 retained as                 an option because the generic structure of this element
 *                 could support a decimal value                 being submitted with some qualifying
 *                 integer value as well.
 *
 * <p>Java class for AttributeDecimalType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AttributeDecimalType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
 *       &lt;attGroup ref="{}CVIdentifiers"/>
 *       &lt;attribute name="integerValue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="dateValue" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Status" type="{}typeStatus" default="current" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeDecimalType", propOrder = {
    "value"
})
public class AttributeDecimalType {

    @XmlValue
    protected BigDecimal value;
    @XmlAttribute(name = "integerValue")
    protected Integer integerValue;
    @XmlAttribute(name = "dateValue")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateValue;
    @XmlAttribute(name = "source")
    protected String source;
    @XmlAttribute(name = "Status")
    protected TypeStatus status;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;
    @XmlAttribute(name = "ncbi_id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ncbiId;

    /**
     * Gets the value of the value property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * Gets the value of the integerValue property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getIntegerValue() {
        return integerValue;
    }

    /**
     * Sets the value of the integerValue property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setIntegerValue(Integer value) {
        this.integerValue = value;
    }

    /**
     * Gets the value of the dateValue property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateValue() {
        return dateValue;
    }

    /**
     * Sets the value of the dateValue property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateValue(XMLGregorianCalendar value) {
        this.dateValue = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return
     *     possible object is
     *     {@link TypeStatus }
     *
     */
    public TypeStatus getStatus() {
        if (status == null) {
            return TypeStatus.CURRENT;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *     allowed object is
     *     {@link TypeStatus }
     *
     */
    public void setStatus(TypeStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the ncbiId property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getNcbiId() {
        return ncbiId;
    }

    /**
     * Sets the value of the ncbiId property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setNcbiId(BigInteger value) {
        this.ncbiId = value;
    }

}
