//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Commenttypelist.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Commenttypelist">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="public"/>
 *     &lt;enumeration value="internal use"/>
 *     &lt;enumeration value="ConvertedByNCBI"/>
 *     &lt;enumeration value="ExplanationOfInterpretation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "Commenttypelist")
@XmlEnum
public enum Commenttypelist {

    @XmlEnumValue("public")
    PUBLIC("public"),
    @XmlEnumValue("internal use")
    INTERNAL_USE("internal use"),
    @XmlEnumValue("ConvertedByNCBI")
    CONVERTED_BY_NCBI("ConvertedByNCBI"),
    @XmlEnumValue("ExplanationOfInterpretation")
    EXPLANATION_OF_INTERPRETATION("ExplanationOfInterpretation");
    private final String value;

    Commenttypelist(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Commenttypelist fromValue(String v) {
        for (Commenttypelist c: Commenttypelist.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
