//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for GenotypeSetType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GenotypeSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GenotypeSetTypeElement">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>typeGenotypesettypelist">
 *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MeasureSet" type="{}MeasureSetType" maxOccurs="unbounded"/>
 *         &lt;element name="Name" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Symbol" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AttributeSet" type="{}MeasureSetAttributeSetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}CVIdentifiers"/>
 *       &lt;attribute name="num_chr" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenotypeSetType", propOrder = {
    "genotypeSetTypeElement",
    "measureSet",
    "name",
    "symbol",
    "attributeSet",
    "citation",
    "xRef",
    "comment"
})
public class GenotypeSetType {

    @XmlElement(name = "GenotypeSetTypeElement", required = true)
    protected GenotypeSetType.GenotypeSetTypeElement genotypeSetTypeElement;
    @XmlElement(name = "MeasureSet", required = true)
    protected List<MeasureSetType> measureSet;
    @XmlElement(name = "Name")
    protected List<SetElementSetType> name;
    @XmlElement(name = "Symbol")
    protected List<SetElementSetType> symbol;
    @XmlElement(name = "AttributeSet")
    protected List<MeasureSetAttributeSetType> attributeSet;
    @XmlElement(name = "Citation")
    protected List<CitationType> citation;
    @XmlElement(name = "XRef")
    protected List<XrefType> xRef;
    @XmlElement(name = "Comment")
    protected CommentType comment;
    @XmlAttribute(name = "num_chr")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numChr;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;
    @XmlAttribute(name = "ncbi_id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ncbiId;

    /**
     * Gets the value of the genotypeSetTypeElement property.
     *
     * @return
     *     possible object is
     *     {@link GenotypeSetType.GenotypeSetTypeElement }
     *
     */
    public GenotypeSetType.GenotypeSetTypeElement getGenotypeSetTypeElement() {
        return genotypeSetTypeElement;
    }

    /**
     * Sets the value of the genotypeSetTypeElement property.
     *
     * @param value
     *     allowed object is
     *     {@link GenotypeSetType.GenotypeSetTypeElement }
     *
     */
    public void setGenotypeSetTypeElement(GenotypeSetType.GenotypeSetTypeElement value) {
        this.genotypeSetTypeElement = value;
    }

    /**
     * Gets the value of the measureSet property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measureSet property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasureSet().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasureSetType }
     *
     *
     */
    public List<MeasureSetType> getMeasureSet() {
        if (measureSet == null) {
            measureSet = new ArrayList<MeasureSetType>();
        }
        return this.measureSet;
    }

    /**
     * Gets the value of the name property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetElementSetType }
     *
     *
     */
    public List<SetElementSetType> getName() {
        if (name == null) {
            name = new ArrayList<SetElementSetType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the symbol property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the symbol property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSymbol().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetElementSetType }
     *
     *
     */
    public List<SetElementSetType> getSymbol() {
        if (symbol == null) {
            symbol = new ArrayList<SetElementSetType>();
        }
        return this.symbol;
    }

    /**
     * Gets the value of the attributeSet property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeSet property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeSet().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasureSetAttributeSetType }
     *
     *
     */
    public List<MeasureSetAttributeSetType> getAttributeSet() {
        if (attributeSet == null) {
            attributeSet = new ArrayList<MeasureSetAttributeSetType>();
        }
        return this.attributeSet;
    }

    /**
     * Gets the value of the citation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CitationType }
     *
     *
     */
    public List<CitationType> getCitation() {
        if (citation == null) {
            citation = new ArrayList<CitationType>();
        }
        return this.citation;
    }

    /**
     * Gets the value of the xRef property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xRef property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXRef().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XrefType }
     *
     *
     */
    public List<XrefType> getXRef() {
        if (xRef == null) {
            xRef = new ArrayList<XrefType>();
        }
        return this.xRef;
    }

    /**
     * Gets the value of the comment property.
     *
     * @return
     *     possible object is
     *     {@link CommentType }
     *
     */
    public CommentType getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value
     *     allowed object is
     *     {@link CommentType }
     *
     */
    public void setComment(CommentType value) {
        this.comment = value;
    }

    /**
     * Gets the value of the numChr property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getNumChr() {
        return numChr;
    }

    /**
     * Sets the value of the numChr property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setNumChr(BigInteger value) {
        this.numChr = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the ncbiId property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getNcbiId() {
        return ncbiId;
    }

    /**
     * Sets the value of the ncbiId property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setNcbiId(BigInteger value) {
        this.ncbiId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>typeGenotypesettypelist">
     *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class GenotypeSetTypeElement {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "val_type", required = true)
        protected TypeIdName valType;

        /**
         * Gets the value of the value property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the valType property.
         *
         * @return
         *     possible object is
         *     {@link TypeIdName }
         *
         */
        public TypeIdName getValType() {
            return valType;
        }

        /**
         * Sets the value of the valType property.
         *
         * @param value
         *     allowed object is
         *     {@link TypeIdName }
         *
         */
        public void setValType(TypeIdName value) {
            this.valType = value;
        }

    }

}
