//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasureRelationshiptype.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MeasureRelationshiptype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="variant in gene"/>
 *     &lt;enumeration value="co-occurring variant"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "MeasureRelationshiptype")
@XmlEnum
public enum MeasureRelationshiptype {

    @XmlEnumValue("variant in gene")
    VARIANT_IN_GENE("variant in gene"),
    @XmlEnumValue("co-occurring variant")
    CO_OCCURRING_VARIANT("co-occurring variant");
    private final String value;

    MeasureRelationshiptype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MeasureRelationshiptype fromValue(String v) {
        for (MeasureRelationshiptype c: MeasureRelationshiptype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
