//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasureRelationshipAttributetype.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MeasureRelationshipAttributetype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HGVS"/>
 *     &lt;enumeration value="genotype"/>
 *     &lt;enumeration value="gene relationships"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "MeasureRelationshipAttributetype")
@XmlEnum
public enum MeasureRelationshipAttributetype {

    HGVS("HGVS"),
    @XmlEnumValue("genotype")
    GENOTYPE("genotype"),
    @XmlEnumValue("gene relationships")
    GENE_RELATIONSHIPS("gene relationships");
    private final String value;

    MeasureRelationshipAttributetype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MeasureRelationshipAttributetype fromValue(String v) {
        for (MeasureRelationshipAttributetype c: MeasureRelationshipAttributetype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
