//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for MeasureSetType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MeasureSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MeasureSetTypeElement">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>typeMeasuresettypelist">
 *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Measure" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MeasureType">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;>typeMeasuretype">
 *                           &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Name" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Symbol" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="AttributeSet" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MeasureAttributeType">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;>typeMeasureAttributetype">
 *                                     &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Attribute" type="{}AttributeType"/>
 *                             &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CytogeneticLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="SequenceLocation" type="{}SequenceLocationType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="MeasureRelationship" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MeasureRelationshipType">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;>typeMeasureRelationshiptype">
 *                                     &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Name" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="Symbol" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="AttributeSet" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="MeasureRelationshipAttributeType">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;>typeMeasureRelationshipAttributetype">
 *                                               &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Attribute" type="{}AttributeType"/>
 *                                       &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{}CVIdentifiers"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{}CVIdentifiers"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Name" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Symbol" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AttributeSet" type="{}MeasureSetAttributeSetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}CVIdentifiers"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasureSetType", propOrder = {
    "measureSetTypeElement",
    "measure",
    "name",
    "symbol",
    "attributeSet",
    "citation",
    "xRef",
    "comment"
})
public class MeasureSetType {

    @XmlElement(name = "MeasureSetTypeElement", required = true)
    protected MeasureSetType.MeasureSetTypeElement measureSetTypeElement;
    @XmlElement(name = "Measure", required = true)
    protected List<MeasureSetType.Measure> measure;
    @XmlElement(name = "Name")
    protected List<SetElementSetType> name;
    @XmlElement(name = "Symbol")
    protected List<SetElementSetType> symbol;
    @XmlElement(name = "AttributeSet")
    protected List<MeasureSetAttributeSetType> attributeSet;
    @XmlElement(name = "Citation")
    protected List<CitationType> citation;
    @XmlElement(name = "XRef")
    protected List<XrefType> xRef;
    @XmlElement(name = "Comment")
    protected CommentType comment;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;
    @XmlAttribute(name = "ncbi_id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ncbiId;

    /**
     * Gets the value of the measureSetTypeElement property.
     *
     * @return
     *     possible object is
     *     {@link MeasureSetType.MeasureSetTypeElement }
     *
     */
    public MeasureSetType.MeasureSetTypeElement getMeasureSetTypeElement() {
        return measureSetTypeElement;
    }

    /**
     * Sets the value of the measureSetTypeElement property.
     *
     * @param value
     *     allowed object is
     *     {@link MeasureSetType.MeasureSetTypeElement }
     *
     */
    public void setMeasureSetTypeElement(MeasureSetType.MeasureSetTypeElement value) {
        this.measureSetTypeElement = value;
    }

    /**
     * Gets the value of the measure property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measure property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasure().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasureSetType.Measure }
     *
     *
     */
    public List<MeasureSetType.Measure> getMeasure() {
        if (measure == null) {
            measure = new ArrayList<MeasureSetType.Measure>();
        }
        return this.measure;
    }

    /**
     * Gets the value of the name property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetElementSetType }
     *
     *
     */
    public List<SetElementSetType> getName() {
        if (name == null) {
            name = new ArrayList<SetElementSetType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the symbol property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the symbol property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSymbol().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetElementSetType }
     *
     *
     */
    public List<SetElementSetType> getSymbol() {
        if (symbol == null) {
            symbol = new ArrayList<SetElementSetType>();
        }
        return this.symbol;
    }

    /**
     * Gets the value of the attributeSet property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeSet property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeSet().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasureSetAttributeSetType }
     *
     *
     */
    public List<MeasureSetAttributeSetType> getAttributeSet() {
        if (attributeSet == null) {
            attributeSet = new ArrayList<MeasureSetAttributeSetType>();
        }
        return this.attributeSet;
    }

    /**
     * Gets the value of the citation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CitationType }
     *
     *
     */
    public List<CitationType> getCitation() {
        if (citation == null) {
            citation = new ArrayList<CitationType>();
        }
        return this.citation;
    }

    /**
     * Gets the value of the xRef property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xRef property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXRef().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XrefType }
     *
     *
     */
    public List<XrefType> getXRef() {
        if (xRef == null) {
            xRef = new ArrayList<XrefType>();
        }
        return this.xRef;
    }

    /**
     * Gets the value of the comment property.
     *
     * @return
     *     possible object is
     *     {@link CommentType }
     *
     */
    public CommentType getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value
     *     allowed object is
     *     {@link CommentType }
     *
     */
    public void setComment(CommentType value) {
        this.comment = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the ncbiId property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getNcbiId() {
        return ncbiId;
    }

    /**
     * Sets the value of the ncbiId property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setNcbiId(BigInteger value) {
        this.ncbiId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MeasureType">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;>typeMeasuretype">
     *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Name" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Symbol" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="AttributeSet" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MeasureAttributeType">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;>typeMeasureAttributetype">
     *                           &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Attribute" type="{}AttributeType"/>
     *                   &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CytogeneticLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="SequenceLocation" type="{}SequenceLocationType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="MeasureRelationship" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MeasureRelationshipType">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;>typeMeasureRelationshiptype">
     *                           &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Name" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Symbol" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="AttributeSet" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="MeasureRelationshipAttributeType">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;>typeMeasureRelationshipAttributetype">
     *                                     &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Attribute" type="{}AttributeType"/>
     *                             &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attGroup ref="{}CVIdentifiers"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{}CVIdentifiers"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "measureType",
        "name",
        "symbol",
        "attributeSet",
        "cytogeneticLocation",
        "sequenceLocation",
        "measureRelationship",
        "citation",
        "xRef",
        "comment"
    })
    public static class Measure {

        @XmlElement(name = "MeasureType", required = true)
        protected MeasureSetType.Measure.MeasureType measureType;
        @XmlElement(name = "Name")
        protected List<SetElementSetType> name;
        @XmlElement(name = "Symbol")
        protected List<SetElementSetType> symbol;
        @XmlElement(name = "AttributeSet")
        protected List<MeasureSetType.Measure.AttributeSet> attributeSet;
        @XmlElement(name = "CytogeneticLocation")
        protected String cytogeneticLocation;
        @XmlElement(name = "SequenceLocation")
        protected List<SequenceLocationType> sequenceLocation;
        @XmlElement(name = "MeasureRelationship")
        protected List<MeasureSetType.Measure.MeasureRelationship> measureRelationship;
        @XmlElement(name = "Citation")
        protected List<CitationType> citation;
        @XmlElement(name = "XRef")
        protected List<XrefType> xRef;
        @XmlElement(name = "Comment")
        protected CommentType comment;
        @XmlAttribute(name = "id")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger id;
        @XmlAttribute(name = "ncbi_id")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger ncbiId;

        /**
         * Gets the value of the measureType property.
         *
         * @return
         *     possible object is
         *     {@link MeasureSetType.Measure.MeasureType }
         *
         */
        public MeasureSetType.Measure.MeasureType getMeasureType() {
            return measureType;
        }

        /**
         * Sets the value of the measureType property.
         *
         * @param value
         *     allowed object is
         *     {@link MeasureSetType.Measure.MeasureType }
         *
         */
        public void setMeasureType(MeasureSetType.Measure.MeasureType value) {
            this.measureType = value;
        }

        /**
         * Gets the value of the name property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the name property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getName().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SetElementSetType }
         *
         *
         */
        public List<SetElementSetType> getName() {
            if (name == null) {
                name = new ArrayList<SetElementSetType>();
            }
            return this.name;
        }

        /**
         * Gets the value of the symbol property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the symbol property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSymbol().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SetElementSetType }
         *
         *
         */
        public List<SetElementSetType> getSymbol() {
            if (symbol == null) {
                symbol = new ArrayList<SetElementSetType>();
            }
            return this.symbol;
        }

        /**
         * Gets the value of the attributeSet property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attributeSet property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttributeSet().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MeasureSetType.Measure.AttributeSet }
         *
         *
         */
        public List<MeasureSetType.Measure.AttributeSet> getAttributeSet() {
            if (attributeSet == null) {
                attributeSet = new ArrayList<MeasureSetType.Measure.AttributeSet>();
            }
            return this.attributeSet;
        }

        /**
         * Gets the value of the cytogeneticLocation property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCytogeneticLocation() {
            return cytogeneticLocation;
        }

        /**
         * Sets the value of the cytogeneticLocation property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCytogeneticLocation(String value) {
            this.cytogeneticLocation = value;
        }

        /**
         * Gets the value of the sequenceLocation property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sequenceLocation property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSequenceLocation().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SequenceLocationType }
         *
         *
         */
        public List<SequenceLocationType> getSequenceLocation() {
            if (sequenceLocation == null) {
                sequenceLocation = new ArrayList<SequenceLocationType>();
            }
            return this.sequenceLocation;
        }

        /**
         * Gets the value of the measureRelationship property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the measureRelationship property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMeasureRelationship().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MeasureSetType.Measure.MeasureRelationship }
         *
         *
         */
        public List<MeasureSetType.Measure.MeasureRelationship> getMeasureRelationship() {
            if (measureRelationship == null) {
                measureRelationship = new ArrayList<MeasureSetType.Measure.MeasureRelationship>();
            }
            return this.measureRelationship;
        }

        /**
         * Gets the value of the citation property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the citation property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCitation().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CitationType }
         *
         *
         */
        public List<CitationType> getCitation() {
            if (citation == null) {
                citation = new ArrayList<CitationType>();
            }
            return this.citation;
        }

        /**
         * Gets the value of the xRef property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the xRef property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getXRef().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XrefType }
         *
         *
         */
        public List<XrefType> getXRef() {
            if (xRef == null) {
                xRef = new ArrayList<XrefType>();
            }
            return this.xRef;
        }

        /**
         * Gets the value of the comment property.
         *
         * @return
         *     possible object is
         *     {@link CommentType }
         *
         */
        public CommentType getComment() {
            return comment;
        }

        /**
         * Sets the value of the comment property.
         *
         * @param value
         *     allowed object is
         *     {@link CommentType }
         *
         */
        public void setComment(CommentType value) {
            this.comment = value;
        }

        /**
         * Gets the value of the id property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setId(BigInteger value) {
            this.id = value;
        }

        /**
         * Gets the value of the ncbiId property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getNcbiId() {
            return ncbiId;
        }

        /**
         * Sets the value of the ncbiId property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setNcbiId(BigInteger value) {
            this.ncbiId = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MeasureAttributeType">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;>typeMeasureAttributetype">
         *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Attribute" type="{}AttributeType"/>
         *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "measureAttributeType",
            "attribute",
            "citation",
            "xRef",
            "comment"
        })
        public static class AttributeSet {

            @XmlElement(name = "MeasureAttributeType", required = true)
            protected MeasureSetType.Measure.AttributeSet.MeasureAttributeType measureAttributeType;
            @XmlElement(name = "Attribute", required = true)
            protected AttributeType attribute;
            @XmlElement(name = "Citation")
            protected List<CitationType> citation;
            @XmlElement(name = "XRef")
            protected List<XrefType> xRef;
            @XmlElement(name = "Comment")
            protected CommentType comment;

            /**
             * Gets the value of the measureAttributeType property.
             *
             * @return
             *     possible object is
             *     {@link MeasureSetType.Measure.AttributeSet.MeasureAttributeType }
             *
             */
            public MeasureSetType.Measure.AttributeSet.MeasureAttributeType getMeasureAttributeType() {
                return measureAttributeType;
            }

            /**
             * Sets the value of the measureAttributeType property.
             *
             * @param value
             *     allowed object is
             *     {@link MeasureSetType.Measure.AttributeSet.MeasureAttributeType }
             *
             */
            public void setMeasureAttributeType(MeasureSetType.Measure.AttributeSet.MeasureAttributeType value) {
                this.measureAttributeType = value;
            }

            /**
             * Gets the value of the attribute property.
             *
             * @return
             *     possible object is
             *     {@link AttributeType }
             *
             */
            public AttributeType getAttribute() {
                return attribute;
            }

            /**
             * Sets the value of the attribute property.
             *
             * @param value
             *     allowed object is
             *     {@link AttributeType }
             *
             */
            public void setAttribute(AttributeType value) {
                this.attribute = value;
            }

            /**
             * Gets the value of the citation property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the citation property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCitation().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CitationType }
             *
             *
             */
            public List<CitationType> getCitation() {
                if (citation == null) {
                    citation = new ArrayList<CitationType>();
                }
                return this.citation;
            }

            /**
             * Gets the value of the xRef property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the xRef property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getXRef().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link XrefType }
             *
             *
             */
            public List<XrefType> getXRef() {
                if (xRef == null) {
                    xRef = new ArrayList<XrefType>();
                }
                return this.xRef;
            }

            /**
             * Gets the value of the comment property.
             *
             * @return
             *     possible object is
             *     {@link CommentType }
             *
             */
            public CommentType getComment() {
                return comment;
            }

            /**
             * Sets the value of the comment property.
             *
             * @param value
             *     allowed object is
             *     {@link CommentType }
             *
             */
            public void setComment(CommentType value) {
                this.comment = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;>typeMeasureAttributetype">
             *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class MeasureAttributeType {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "val_type", required = true)
                protected TypeIdName valType;

                /**
                 * Gets the value of the value property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the valType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link TypeIdName }
                 *
                 */
                public TypeIdName getValType() {
                    return valType;
                }

                /**
                 * Sets the value of the valType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link TypeIdName }
                 *
                 */
                public void setValType(TypeIdName value) {
                    this.valType = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MeasureRelationshipType">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;>typeMeasureRelationshiptype">
         *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Name" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Symbol" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="AttributeSet" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="MeasureRelationshipAttributeType">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;>typeMeasureRelationshipAttributetype">
         *                           &lt;attribute name="val_type" use="required" type="{}typeIdName" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Attribute" type="{}AttributeType"/>
         *                   &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{}CVIdentifiers"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "measureRelationshipType",
            "name",
            "symbol",
            "attributeSet",
            "citation",
            "xRef",
            "comment"
        })
        public static class MeasureRelationship {

            @XmlElement(name = "MeasureRelationshipType", required = true)
            protected MeasureSetType.Measure.MeasureRelationship.MeasureRelationshipType measureRelationshipType;
            @XmlElement(name = "Name")
            protected List<SetElementSetType> name;
            @XmlElement(name = "Symbol")
            protected List<SetElementSetType> symbol;
            @XmlElement(name = "AttributeSet")
            protected List<MeasureSetType.Measure.MeasureRelationship.AttributeSet> attributeSet;
            @XmlElement(name = "Citation")
            protected List<CitationType> citation;
            @XmlElement(name = "XRef")
            protected List<XrefType> xRef;
            @XmlElement(name = "Comment")
            protected List<CommentType> comment;
            @XmlAttribute(name = "id")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger id;
            @XmlAttribute(name = "ncbi_id")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger ncbiId;

            /**
             * Gets the value of the measureRelationshipType property.
             *
             * @return
             *     possible object is
             *     {@link MeasureSetType.Measure.MeasureRelationship.MeasureRelationshipType }
             *
             */
            public MeasureSetType.Measure.MeasureRelationship.MeasureRelationshipType getMeasureRelationshipType() {
                return measureRelationshipType;
            }

            /**
             * Sets the value of the measureRelationshipType property.
             *
             * @param value
             *     allowed object is
             *     {@link MeasureSetType.Measure.MeasureRelationship.MeasureRelationshipType }
             *
             */
            public void setMeasureRelationshipType(MeasureSetType.Measure.MeasureRelationship.MeasureRelationshipType value) {
                this.measureRelationshipType = value;
            }

            /**
             * Gets the value of the name property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the name property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getName().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SetElementSetType }
             *
             *
             */
            public List<SetElementSetType> getName() {
                if (name == null) {
                    name = new ArrayList<SetElementSetType>();
                }
                return this.name;
            }

            /**
             * Gets the value of the symbol property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the symbol property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSymbol().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SetElementSetType }
             *
             *
             */
            public List<SetElementSetType> getSymbol() {
                if (symbol == null) {
                    symbol = new ArrayList<SetElementSetType>();
                }
                return this.symbol;
            }

            /**
             * Gets the value of the attributeSet property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the attributeSet property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAttributeSet().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MeasureSetType.Measure.MeasureRelationship.AttributeSet }
             *
             *
             */
            public List<MeasureSetType.Measure.MeasureRelationship.AttributeSet> getAttributeSet() {
                if (attributeSet == null) {
                    attributeSet = new ArrayList<MeasureSetType.Measure.MeasureRelationship.AttributeSet>();
                }
                return this.attributeSet;
            }

            /**
             * Gets the value of the citation property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the citation property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCitation().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CitationType }
             *
             *
             */
            public List<CitationType> getCitation() {
                if (citation == null) {
                    citation = new ArrayList<CitationType>();
                }
                return this.citation;
            }

            /**
             * Gets the value of the xRef property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the xRef property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getXRef().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link XrefType }
             *
             *
             */
            public List<XrefType> getXRef() {
                if (xRef == null) {
                    xRef = new ArrayList<XrefType>();
                }
                return this.xRef;
            }

            /**
             * Gets the value of the comment property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the comment property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getComment().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CommentType }
             *
             *
             */
            public List<CommentType> getComment() {
                if (comment == null) {
                    comment = new ArrayList<CommentType>();
                }
                return this.comment;
            }

            /**
             * Gets the value of the id property.
             *
             * @return
             *     possible object is
             *     {@link BigInteger }
             *
             */
            public BigInteger getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *
             */
            public void setId(BigInteger value) {
                this.id = value;
            }

            /**
             * Gets the value of the ncbiId property.
             *
             * @return
             *     possible object is
             *     {@link BigInteger }
             *
             */
            public BigInteger getNcbiId() {
                return ncbiId;
            }

            /**
             * Sets the value of the ncbiId property.
             *
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *
             */
            public void setNcbiId(BigInteger value) {
                this.ncbiId = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="MeasureRelationshipAttributeType">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;>typeMeasureRelationshipAttributetype">
             *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Attribute" type="{}AttributeType"/>
             *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "measureRelationshipAttributeType",
                "attribute",
                "citation",
                "xRef",
                "comment"
            })
            public static class AttributeSet {

                @XmlElement(name = "MeasureRelationshipAttributeType", required = true)
                protected MeasureSetType.Measure.MeasureRelationship.AttributeSet.MeasureRelationshipAttributeType measureRelationshipAttributeType;
                @XmlElement(name = "Attribute", required = true)
                protected AttributeType attribute;
                @XmlElement(name = "Citation")
                protected List<CitationType> citation;
                @XmlElement(name = "XRef")
                protected List<XrefType> xRef;
                @XmlElement(name = "Comment")
                protected List<CommentType> comment;

                /**
                 * Gets the value of the measureRelationshipAttributeType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link MeasureSetType.Measure.MeasureRelationship.AttributeSet.MeasureRelationshipAttributeType }
                 *
                 */
                public MeasureSetType.Measure.MeasureRelationship.AttributeSet.MeasureRelationshipAttributeType getMeasureRelationshipAttributeType() {
                    return measureRelationshipAttributeType;
                }

                /**
                 * Sets the value of the measureRelationshipAttributeType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link MeasureSetType.Measure.MeasureRelationship.AttributeSet.MeasureRelationshipAttributeType }
                 *
                 */
                public void setMeasureRelationshipAttributeType(MeasureSetType.Measure.MeasureRelationship.AttributeSet.MeasureRelationshipAttributeType value) {
                    this.measureRelationshipAttributeType = value;
                }

                /**
                 * Gets the value of the attribute property.
                 *
                 * @return
                 *     possible object is
                 *     {@link AttributeType }
                 *
                 */
                public AttributeType getAttribute() {
                    return attribute;
                }

                /**
                 * Sets the value of the attribute property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link AttributeType }
                 *
                 */
                public void setAttribute(AttributeType value) {
                    this.attribute = value;
                }

                /**
                 * Gets the value of the citation property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the citation property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCitation().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link CitationType }
                 *
                 *
                 */
                public List<CitationType> getCitation() {
                    if (citation == null) {
                        citation = new ArrayList<CitationType>();
                    }
                    return this.citation;
                }

                /**
                 * Gets the value of the xRef property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the xRef property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getXRef().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link XrefType }
                 *
                 *
                 */
                public List<XrefType> getXRef() {
                    if (xRef == null) {
                        xRef = new ArrayList<XrefType>();
                    }
                    return this.xRef;
                }

                /**
                 * Gets the value of the comment property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the comment property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getComment().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link CommentType }
                 *
                 *
                 */
                public List<CommentType> getComment() {
                    if (comment == null) {
                        comment = new ArrayList<CommentType>();
                    }
                    return this.comment;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;>typeMeasureRelationshipAttributetype">
                 *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class MeasureRelationshipAttributeType {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "val_type", required = true)
                    protected TypeIdName valType;

                    /**
                     * Gets the value of the value property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the valType property.
                     *
                     * @return
                     *     possible object is
                     *     {@link TypeIdName }
                     *
                     */
                    public TypeIdName getValType() {
                        return valType;
                    }

                    /**
                     * Sets the value of the valType property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link TypeIdName }
                     *
                     */
                    public void setValType(TypeIdName value) {
                        this.valType = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;>typeMeasureRelationshiptype">
             *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class MeasureRelationshipType {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "val_type", required = true)
                protected TypeIdName valType;

                /**
                 * Gets the value of the value property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the valType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link TypeIdName }
                 *
                 */
                public TypeIdName getValType() {
                    return valType;
                }

                /**
                 * Sets the value of the valType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link TypeIdName }
                 *
                 */
                public void setValType(TypeIdName value) {
                    this.valType = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;>typeMeasuretype">
         *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class MeasureType {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "val_type", required = true)
            protected TypeIdName valType;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the valType property.
             *
             * @return
             *     possible object is
             *     {@link TypeIdName }
             *
             */
            public TypeIdName getValType() {
                return valType;
            }

            /**
             * Sets the value of the valType property.
             *
             * @param value
             *     allowed object is
             *     {@link TypeIdName }
             *
             */
            public void setValType(TypeIdName value) {
                this.valType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>typeMeasuresettypelist">
     *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MeasureSetTypeElement {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "val_type", required = true)
        protected TypeIdName valType;

        /**
         * Gets the value of the value property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the valType property.
         *
         * @return
         *     possible object is
         *     {@link TypeIdName }
         *
         */
        public TypeIdName getValType() {
            return valType;
        }

        /**
         * Sets the value of the valType property.
         *
         * @param value
         *     allowed object is
         *     {@link TypeIdName }
         *
         */
        public void setValType(TypeIdName value) {
            this.valType = value;
        }

    }

}
