//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.pharmgkb.io.exporter.clinvar package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClinvarSubmissionSet_QNAME = new QName("", "ClinvarSubmissionSet");
    private final static QName _PersonnelTypePersonRef_QNAME = new QName("", "PersonRef");
    private final static QName _PersonnelTypePersonPermissions_QNAME = new QName("", "PersonPermissions");
    private final static QName _PersonnelTypePrivateContact_QNAME = new QName("", "PrivateContact");
    private final static QName _PersonnelTypePublicContact_QNAME = new QName("", "PublicContact");
    private final static QName _PersonnelTypeTitle_QNAME = new QName("", "Title");
    private final static QName _PersonnelTypePerson_QNAME = new QName("", "Person");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.pharmgkb.io.exporter.clinvar
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IndicationType }
     *
     */
    public IndicationType createIndicationType() {
        return new IndicationType();
    }

    /**
     * Create an instance of {@link SubmissionType }
     *
     */
    public SubmissionType createSubmissionType() {
        return new SubmissionType();
    }

    /**
     * Create an instance of {@link SubmissionType.ClinvarSubmissionAcc }
     *
     */
    public SubmissionType.ClinvarSubmissionAcc createSubmissionTypeClinvarSubmissionAcc() {
        return new SubmissionType.ClinvarSubmissionAcc();
    }

    /**
     * Create an instance of {@link TraitSetAttributeSetType }
     *
     */
    public TraitSetAttributeSetType createTraitSetAttributeSetType() {
        return new TraitSetAttributeSetType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     *
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link TraitType }
     *
     */
    public TraitType createTraitType() {
        return new TraitType();
    }

    /**
     * Create an instance of {@link TraitType.TraitRelationship }
     *
     */
    public TraitType.TraitRelationship createTraitTypeTraitRelationship() {
        return new TraitType.TraitRelationship();
    }

    /**
     * Create an instance of {@link TraitType.TraitRelationship.AttributeSet }
     *
     */
    public TraitType.TraitRelationship.AttributeSet createTraitTypeTraitRelationshipAttributeSet() {
        return new TraitType.TraitRelationship.AttributeSet();
    }

    /**
     * Create an instance of {@link TraitType.AttributeSet }
     *
     */
    public TraitType.AttributeSet createTraitTypeAttributeSet() {
        return new TraitType.AttributeSet();
    }

    /**
     * Create an instance of {@link GenotypeSetType }
     *
     */
    public GenotypeSetType createGenotypeSetType() {
        return new GenotypeSetType();
    }

    /**
     * Create an instance of {@link CommentType }
     *
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link MeasureTraitType }
     *
     */
    public MeasureTraitType createMeasureTraitType() {
        return new MeasureTraitType();
    }

    /**
     * Create an instance of {@link MeasureTraitType.AttributeSet }
     *
     */
    public MeasureTraitType.AttributeSet createMeasureTraitTypeAttributeSet() {
        return new MeasureTraitType.AttributeSet();
    }

    /**
     * Create an instance of {@link MeasureTraitType.Assertion }
     *
     */
    public MeasureTraitType.Assertion createMeasureTraitTypeAssertion() {
        return new MeasureTraitType.Assertion();
    }

    /**
     * Create an instance of {@link AttributeBundleType }
     *
     */
    public AttributeBundleType createAttributeBundleType() {
        return new AttributeBundleType();
    }

    /**
     * Create an instance of {@link SetElementSetType }
     *
     */
    public SetElementSetType createSetElementSetType() {
        return new SetElementSetType();
    }

    /**
     * Create an instance of {@link SampleType }
     *
     */
    public SampleType createSampleType() {
        return new SampleType();
    }

    /**
     * Create an instance of {@link AddressType }
     *
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link MethodAttributeType }
     *
     */
    public MethodAttributeType createMethodAttributeType() {
        return new MethodAttributeType();
    }

    /**
     * Create an instance of {@link TraitSetType }
     *
     */
    public TraitSetType createTraitSetType() {
        return new TraitSetType();
    }

    /**
     * Create an instance of {@link CitationType }
     *
     */
    public CitationType createCitationType() {
        return new CitationType();
    }

    /**
     * Create an instance of {@link SubmitterType }
     *
     */
    public SubmitterType createSubmitterType() {
        return new SubmitterType();
    }

    /**
     * Create an instance of {@link SubmitterType.Person }
     *
     */
    public SubmitterType.Person createSubmitterTypePerson() {
        return new SubmitterType.Person();
    }

    /**
     * Create an instance of {@link MethodType }
     *
     */
    public MethodType createMethodType() {
        return new MethodType();
    }

    /**
     * Create an instance of {@link MeasureSetType }
     *
     */
    public MeasureSetType createMeasureSetType() {
        return new MeasureSetType();
    }

    /**
     * Create an instance of {@link MeasureSetType.Measure }
     *
     */
    public MeasureSetType.Measure createMeasureSetTypeMeasure() {
        return new MeasureSetType.Measure();
    }

    /**
     * Create an instance of {@link MeasureSetType.Measure.MeasureRelationship }
     *
     */
    public MeasureSetType.Measure.MeasureRelationship createMeasureSetTypeMeasureMeasureRelationship() {
        return new MeasureSetType.Measure.MeasureRelationship();
    }

    /**
     * Create an instance of {@link MeasureSetType.Measure.MeasureRelationship.AttributeSet }
     *
     */
    public MeasureSetType.Measure.MeasureRelationship.AttributeSet createMeasureSetTypeMeasureMeasureRelationshipAttributeSet() {
        return new MeasureSetType.Measure.MeasureRelationship.AttributeSet();
    }

    /**
     * Create an instance of {@link MeasureSetType.Measure.AttributeSet }
     *
     */
    public MeasureSetType.Measure.AttributeSet createMeasureSetTypeMeasureAttributeSet() {
        return new MeasureSetType.Measure.AttributeSet();
    }

    /**
     * Create an instance of {@link MeasureSetAttributeSetType }
     *
     */
    public MeasureSetAttributeSetType createMeasureSetAttributeSetType() {
        return new MeasureSetAttributeSetType();
    }

    /**
     * Create an instance of {@link PersonType }
     *
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link ObservedDataType }
     *
     */
    public ObservedDataType createObservedDataType() {
        return new ObservedDataType();
    }

    /**
     * Create an instance of {@link ObsMethodAttributeType }
     *
     */
    public ObsMethodAttributeType createObsMethodAttributeType() {
        return new ObsMethodAttributeType();
    }

    /**
     * Create an instance of {@link SubmissionSetType }
     *
     */
    public SubmissionSetType createSubmissionSetType() {
        return new SubmissionSetType();
    }

    /**
     * Create an instance of {@link CertificationType }
     *
     */
    public CertificationType createCertificationType() {
        return new CertificationType();
    }

    /**
     * Create an instance of {@link XrefType }
     *
     */
    public XrefType createXrefType() {
        return new XrefType();
    }

    /**
     * Create an instance of {@link CredentialType }
     *
     */
    public CredentialType createCredentialType() {
        return new CredentialType();
    }

    /**
     * Create an instance of {@link TypeContactInfo }
     *
     */
    public TypeContactInfo createTypeContactInfo() {
        return new TypeContactInfo();
    }

    /**
     * Create an instance of {@link AlleleDescType }
     *
     */
    public AlleleDescType createAlleleDescType() {
        return new AlleleDescType();
    }

    /**
     * Create an instance of {@link ObsMethodAttributeTypeType }
     *
     */
    public ObsMethodAttributeTypeType createObsMethodAttributeTypeType() {
        return new ObsMethodAttributeTypeType();
    }

    /**
     * Create an instance of {@link FamilyInfo }
     *
     */
    public FamilyInfo createFamilyInfo() {
        return new FamilyInfo();
    }

    /**
     * Create an instance of {@link LabCertificationType }
     *
     */
    public LabCertificationType createLabCertificationType() {
        return new LabCertificationType();
    }

    /**
     * Create an instance of {@link SequenceLocationType }
     *
     */
    public SequenceLocationType createSequenceLocationType() {
        return new SequenceLocationType();
    }

    /**
     * Create an instance of {@link SoftwareSet }
     *
     */
    public SoftwareSet createSoftwareSet() {
        return new SoftwareSet();
    }

    /**
     * Create an instance of {@link MethodAttributeTypeType }
     *
     */
    public MethodAttributeTypeType createMethodAttributeTypeType() {
        return new MethodAttributeTypeType();
    }

    /**
     * Create an instance of {@link AcronymType }
     *
     */
    public AcronymType createAcronymType() {
        return new AcronymType();
    }

    /**
     * Create an instance of {@link OrgType }
     *
     */
    public OrgType createOrgType() {
        return new OrgType();
    }

    /**
     * Create an instance of {@link ContactType }
     *
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link PersonCertificationType }
     *
     */
    public PersonCertificationType createPersonCertificationType() {
        return new PersonCertificationType();
    }

    /**
     * Create an instance of {@link AttributeType }
     *
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link AttributeTypeType }
     *
     */
    public AttributeTypeType createAttributeTypeType() {
        return new AttributeTypeType();
    }

    /**
     * Create an instance of {@link ObservationSet }
     *
     */
    public ObservationSet createObservationSet() {
        return new ObservationSet();
    }

    /**
     * Create an instance of {@link TypeAccount }
     *
     */
    public TypeAccount createTypeAccount() {
        return new TypeAccount();
    }

    /**
     * Create an instance of {@link OrgIDType }
     *
     */
    public OrgIDType createOrgIDType() {
        return new OrgIDType();
    }

    /**
     * Create an instance of {@link ClinicalSignificanceType }
     *
     */
    public ClinicalSignificanceType createClinicalSignificanceType() {
        return new ClinicalSignificanceType();
    }

    /**
     * Create an instance of {@link CoOccurrenceType }
     *
     */
    public CoOccurrenceType createCoOccurrenceType() {
        return new CoOccurrenceType();
    }

    /**
     * Create an instance of {@link AttributeDecimalType }
     *
     */
    public AttributeDecimalType createAttributeDecimalType() {
        return new AttributeDecimalType();
    }

    /**
     * Create an instance of {@link PersonnelType }
     *
     */
    public PersonnelType createPersonnelType() {
        return new PersonnelType();
    }

    /**
     * Create an instance of {@link DegreeType }
     *
     */
    public DegreeType createDegreeType() {
        return new DegreeType();
    }

    /**
     * Create an instance of {@link IndicationType.TraitSetType }
     *
     */
    public IndicationType.TraitSetType createIndicationTypeTraitSetType() {
        return new IndicationType.TraitSetType();
    }

    /**
     * Create an instance of {@link SubmissionType.ClinvarSubmissionID }
     *
     */
    public SubmissionType.ClinvarSubmissionID createSubmissionTypeClinvarSubmissionID() {
        return new SubmissionType.ClinvarSubmissionID();
    }

    /**
     * Create an instance of {@link SubmissionType.ClinvarSubmissionAcc.ClinvarSubmissionAccType }
     *
     */
    public SubmissionType.ClinvarSubmissionAcc.ClinvarSubmissionAccType createSubmissionTypeClinvarSubmissionAccClinvarSubmissionAccType() {
        return new SubmissionType.ClinvarSubmissionAcc.ClinvarSubmissionAccType();
    }

    /**
     * Create an instance of {@link TraitSetAttributeSetType.TraitSetAttributeType }
     *
     */
    public TraitSetAttributeSetType.TraitSetAttributeType createTraitSetAttributeSetTypeTraitSetAttributeType() {
        return new TraitSetAttributeSetType.TraitSetAttributeType();
    }

    /**
     * Create an instance of {@link OrganizationType.Institution }
     *
     */
    public OrganizationType.Institution createOrganizationTypeInstitution() {
        return new OrganizationType.Institution();
    }

    /**
     * Create an instance of {@link TraitType.TraitTypeElement }
     *
     */
    public TraitType.TraitTypeElement createTraitTypeTraitTypeElement() {
        return new TraitType.TraitTypeElement();
    }

    /**
     * Create an instance of {@link TraitType.TraitRelationship.TraitRelationshipType }
     *
     */
    public TraitType.TraitRelationship.TraitRelationshipType createTraitTypeTraitRelationshipTraitRelationshipType() {
        return new TraitType.TraitRelationship.TraitRelationshipType();
    }

    /**
     * Create an instance of {@link TraitType.TraitRelationship.AttributeSet.TraitRelationshipAttributeType }
     *
     */
    public TraitType.TraitRelationship.AttributeSet.TraitRelationshipAttributeType createTraitTypeTraitRelationshipAttributeSetTraitRelationshipAttributeType() {
        return new TraitType.TraitRelationship.AttributeSet.TraitRelationshipAttributeType();
    }

    /**
     * Create an instance of {@link TraitType.AttributeSet.TraitAttributeType }
     *
     */
    public TraitType.AttributeSet.TraitAttributeType createTraitTypeAttributeSetTraitAttributeType() {
        return new TraitType.AttributeSet.TraitAttributeType();
    }

    /**
     * Create an instance of {@link GenotypeSetType.GenotypeSetTypeElement }
     *
     */
    public GenotypeSetType.GenotypeSetTypeElement createGenotypeSetTypeGenotypeSetTypeElement() {
        return new GenotypeSetType.GenotypeSetTypeElement();
    }

    /**
     * Create an instance of {@link CommentType.Type }
     *
     */
    public CommentType.Type createCommentTypeType() {
        return new CommentType.Type();
    }

    /**
     * Create an instance of {@link MeasureTraitType.CustomAssertionScore }
     *
     */
    public MeasureTraitType.CustomAssertionScore createMeasureTraitTypeCustomAssertionScore() {
        return new MeasureTraitType.CustomAssertionScore();
    }

    /**
     * Create an instance of {@link MeasureTraitType.AttributeSet.MeasureTraitAttributeType }
     *
     */
    public MeasureTraitType.AttributeSet.MeasureTraitAttributeType createMeasureTraitTypeAttributeSetMeasureTraitAttributeType() {
        return new MeasureTraitType.AttributeSet.MeasureTraitAttributeType();
    }

    /**
     * Create an instance of {@link MeasureTraitType.Assertion.AssertionType }
     *
     */
    public MeasureTraitType.Assertion.AssertionType createMeasureTraitTypeAssertionAssertionType() {
        return new MeasureTraitType.Assertion.AssertionType();
    }

    /**
     * Create an instance of {@link AttributeBundleType.AttributeType }
     *
     */
    public AttributeBundleType.AttributeType createAttributeBundleTypeAttributeType() {
        return new AttributeBundleType.AttributeType();
    }

    /**
     * Create an instance of {@link SetElementSetType.ElementValueType }
     *
     */
    public SetElementSetType.ElementValueType createSetElementSetTypeElementValueType() {
        return new SetElementSetType.ElementValueType();
    }

    /**
     * Create an instance of {@link SetElementSetType.ElementValue }
     *
     */
    public SetElementSetType.ElementValue createSetElementSetTypeElementValue() {
        return new SetElementSetType.ElementValue();
    }

    /**
     * Create an instance of {@link SampleType.SampleDescription }
     *
     */
    public SampleType.SampleDescription createSampleTypeSampleDescription() {
        return new SampleType.SampleDescription();
    }

    /**
     * Create an instance of {@link SampleType.Species }
     *
     */
    public SampleType.Species createSampleTypeSpecies() {
        return new SampleType.Species();
    }

    /**
     * Create an instance of {@link SampleType.Age }
     *
     */
    public SampleType.Age createSampleTypeAge() {
        return new SampleType.Age();
    }

    /**
     * Create an instance of {@link AddressType.State }
     *
     */
    public AddressType.State createAddressTypeState() {
        return new AddressType.State();
    }

    /**
     * Create an instance of {@link AddressType.Country }
     *
     */
    public AddressType.Country createAddressTypeCountry() {
        return new AddressType.Country();
    }

    /**
     * Create an instance of {@link MethodAttributeType.AttributeType }
     *
     */
    public MethodAttributeType.AttributeType createMethodAttributeTypeAttributeType() {
        return new MethodAttributeType.AttributeType();
    }

    /**
     * Create an instance of {@link TraitSetType.TraitSetTypeElement }
     *
     */
    public TraitSetType.TraitSetTypeElement createTraitSetTypeTraitSetTypeElement() {
        return new TraitSetType.TraitSetTypeElement();
    }

    /**
     * Create an instance of {@link CitationType.CitationTypeElement }
     *
     */
    public CitationType.CitationTypeElement createCitationTypeCitationTypeElement() {
        return new CitationType.CitationTypeElement();
    }

    /**
     * Create an instance of {@link CitationType.ID }
     *
     */
    public CitationType.ID createCitationTypeID() {
        return new CitationType.ID();
    }

    /**
     * Create an instance of {@link SubmitterType.Organization }
     *
     */
    public SubmitterType.Organization createSubmitterTypeOrganization() {
        return new SubmitterType.Organization();
    }

    /**
     * Create an instance of {@link SubmitterType.Person.Name }
     *
     */
    public SubmitterType.Person.Name createSubmitterTypePersonName() {
        return new SubmitterType.Person.Name();
    }

    /**
     * Create an instance of {@link MethodType.MethodTypeElement }
     *
     */
    public MethodType.MethodTypeElement createMethodTypeMethodTypeElement() {
        return new MethodType.MethodTypeElement();
    }

    /**
     * Create an instance of {@link MeasureSetType.MeasureSetTypeElement }
     *
     */
    public MeasureSetType.MeasureSetTypeElement createMeasureSetTypeMeasureSetTypeElement() {
        return new MeasureSetType.MeasureSetTypeElement();
    }

    /**
     * Create an instance of {@link MeasureSetType.Measure.MeasureType }
     *
     */
    public MeasureSetType.Measure.MeasureType createMeasureSetTypeMeasureMeasureType() {
        return new MeasureSetType.Measure.MeasureType();
    }

    /**
     * Create an instance of {@link MeasureSetType.Measure.MeasureRelationship.MeasureRelationshipType }
     *
     */
    public MeasureSetType.Measure.MeasureRelationship.MeasureRelationshipType createMeasureSetTypeMeasureMeasureRelationshipMeasureRelationshipType() {
        return new MeasureSetType.Measure.MeasureRelationship.MeasureRelationshipType();
    }

    /**
     * Create an instance of {@link MeasureSetType.Measure.MeasureRelationship.AttributeSet.MeasureRelationshipAttributeType }
     *
     */
    public MeasureSetType.Measure.MeasureRelationship.AttributeSet.MeasureRelationshipAttributeType createMeasureSetTypeMeasureMeasureRelationshipAttributeSetMeasureRelationshipAttributeType() {
        return new MeasureSetType.Measure.MeasureRelationship.AttributeSet.MeasureRelationshipAttributeType();
    }

    /**
     * Create an instance of {@link MeasureSetType.Measure.AttributeSet.MeasureAttributeType }
     *
     */
    public MeasureSetType.Measure.AttributeSet.MeasureAttributeType createMeasureSetTypeMeasureAttributeSetMeasureAttributeType() {
        return new MeasureSetType.Measure.AttributeSet.MeasureAttributeType();
    }

    /**
     * Create an instance of {@link MeasureSetAttributeSetType.MeasureSetAttributeType }
     *
     */
    public MeasureSetAttributeSetType.MeasureSetAttributeType createMeasureSetAttributeSetTypeMeasureSetAttributeType() {
        return new MeasureSetAttributeSetType.MeasureSetAttributeType();
    }

    /**
     * Create an instance of {@link PersonType.Name }
     *
     */
    public PersonType.Name createPersonTypeName() {
        return new PersonType.Name();
    }

    /**
     * Create an instance of {@link PersonType.Degree }
     *
     */
    public PersonType.Degree createPersonTypeDegree() {
        return new PersonType.Degree();
    }

    /**
     * Create an instance of {@link PersonType.Credential }
     *
     */
    public PersonType.Credential createPersonTypeCredential() {
        return new PersonType.Credential();
    }

    /**
     * Create an instance of {@link ObservedDataType.ObsAttributeType }
     *
     */
    public ObservedDataType.ObsAttributeType createObservedDataTypeObsAttributeType() {
        return new ObservedDataType.ObsAttributeType();
    }

    /**
     * Create an instance of {@link ObservedDataType.ObsDecAttributeType }
     *
     */
    public ObservedDataType.ObsDecAttributeType createObservedDataTypeObsDecAttributeType() {
        return new ObservedDataType.ObsDecAttributeType();
    }

    /**
     * Create an instance of {@link ObsMethodAttributeType.AttributeType }
     *
     */
    public ObsMethodAttributeType.AttributeType createObsMethodAttributeTypeAttributeType() {
        return new ObsMethodAttributeType.AttributeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmissionSetType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ClinvarSubmissionSet")
    public JAXBElement<SubmissionSetType> createClinvarSubmissionSet(SubmissionSetType value) {
        return new JAXBElement<SubmissionSetType>(_ClinvarSubmissionSet_QNAME, SubmissionSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XrefType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PersonRef", scope = PersonnelType.class)
    public JAXBElement<XrefType> createPersonnelTypePersonRef(XrefType value) {
        return new JAXBElement<XrefType>(_PersonnelTypePersonRef_QNAME, XrefType.class, PersonnelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PersonPermissions", scope = PersonnelType.class)
    public JAXBElement<String> createPersonnelTypePersonPermissions(String value) {
        return new JAXBElement<String>(_PersonnelTypePersonPermissions_QNAME, String.class, PersonnelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PrivateContact", scope = PersonnelType.class)
    public JAXBElement<ContactType> createPersonnelTypePrivateContact(ContactType value) {
        return new JAXBElement<ContactType>(_PersonnelTypePrivateContact_QNAME, ContactType.class, PersonnelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PublicContact", scope = PersonnelType.class)
    public JAXBElement<ContactType> createPersonnelTypePublicContact(ContactType value) {
        return new JAXBElement<ContactType>(_PersonnelTypePublicContact_QNAME, ContactType.class, PersonnelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TitleList }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "Title", scope = PersonnelType.class)
    public JAXBElement<TitleList> createPersonnelTypeTitle(TitleList value) {
        return new JAXBElement<TitleList>(_PersonnelTypeTitle_QNAME, TitleList.class, PersonnelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "Person", scope = PersonnelType.class)
    public JAXBElement<PersonType> createPersonnelTypePerson(PersonType value) {
        return new JAXBElement<PersonType>(_PersonnelTypePerson_QNAME, PersonType.class, PersonnelType.class, value);
    }

}
