//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for OrganizationType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OrganizationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NameAcronym" type="{}AcronymType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Institution" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="cv_id" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InstitutionAcronym" type="{}AcronymType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OrganizationCategory" type="{}OrganizationCategoryList"/>
 *         &lt;element name="Department" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MailingAddress" type="{}AddressType" minOccurs="0"/>
 *         &lt;element name="StreetAddress" type="{}AddressType" minOccurs="0"/>
 *         &lt;element name="LabContact" type="{}ContactType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="OrgAttribute" type="{}AttributeBundleType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationType", propOrder = {
    "name",
    "nameAcronym",
    "institution",
    "institutionAcronym",
    "organizationCategory",
    "department",
    "mailingAddress",
    "streetAddress",
    "labContact",
    "url",
    "orgAttribute"
})
public class OrganizationType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "NameAcronym")
    protected List<AcronymType> nameAcronym;
    @XmlElement(name = "Institution")
    protected OrganizationType.Institution institution;
    @XmlElement(name = "InstitutionAcronym")
    protected List<AcronymType> institutionAcronym;
    @XmlElement(name = "OrganizationCategory", required = true, defaultValue = "lab")
    @XmlSchemaType(name = "string")
    protected OrganizationCategoryList organizationCategory;
    @XmlElement(name = "Department")
    protected String department;
    @XmlElement(name = "MailingAddress")
    protected AddressType mailingAddress;
    @XmlElement(name = "StreetAddress")
    protected AddressType streetAddress;
    @XmlElement(name = "LabContact")
    protected List<ContactType> labContact;
    @XmlElement(name = "URL")
    @XmlSchemaType(name = "anyURI")
    protected String url;
    @XmlElement(name = "OrgAttribute")
    protected List<AttributeBundleType> orgAttribute;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nameAcronym property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameAcronym property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameAcronym().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcronymType }
     *
     *
     */
    public List<AcronymType> getNameAcronym() {
        if (nameAcronym == null) {
            nameAcronym = new ArrayList<AcronymType>();
        }
        return this.nameAcronym;
    }

    /**
     * Gets the value of the institution property.
     *
     * @return
     *     possible object is
     *     {@link OrganizationType.Institution }
     *
     */
    public OrganizationType.Institution getInstitution() {
        return institution;
    }

    /**
     * Sets the value of the institution property.
     *
     * @param value
     *     allowed object is
     *     {@link OrganizationType.Institution }
     *
     */
    public void setInstitution(OrganizationType.Institution value) {
        this.institution = value;
    }

    /**
     * Gets the value of the institutionAcronym property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the institutionAcronym property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstitutionAcronym().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcronymType }
     *
     *
     */
    public List<AcronymType> getInstitutionAcronym() {
        if (institutionAcronym == null) {
            institutionAcronym = new ArrayList<AcronymType>();
        }
        return this.institutionAcronym;
    }

    /**
     * Gets the value of the organizationCategory property.
     *
     * @return
     *     possible object is
     *     {@link OrganizationCategoryList }
     *
     */
    public OrganizationCategoryList getOrganizationCategory() {
        return organizationCategory;
    }

    /**
     * Sets the value of the organizationCategory property.
     *
     * @param value
     *     allowed object is
     *     {@link OrganizationCategoryList }
     *
     */
    public void setOrganizationCategory(OrganizationCategoryList value) {
        this.organizationCategory = value;
    }

    /**
     * Gets the value of the department property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDepartment(String value) {
        this.department = value;
    }

    /**
     * Gets the value of the mailingAddress property.
     *
     * @return
     *     possible object is
     *     {@link AddressType }
     *
     */
    public AddressType getMailingAddress() {
        return mailingAddress;
    }

    /**
     * Sets the value of the mailingAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *
     */
    public void setMailingAddress(AddressType value) {
        this.mailingAddress = value;
    }

    /**
     * Gets the value of the streetAddress property.
     *
     * @return
     *     possible object is
     *     {@link AddressType }
     *
     */
    public AddressType getStreetAddress() {
        return streetAddress;
    }

    /**
     * Sets the value of the streetAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *
     */
    public void setStreetAddress(AddressType value) {
        this.streetAddress = value;
    }

    /**
     * Gets the value of the labContact property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labContact property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabContact().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactType }
     *
     *
     */
    public List<ContactType> getLabContact() {
        if (labContact == null) {
            labContact = new ArrayList<ContactType>();
        }
        return this.labContact;
    }

    /**
     * Gets the value of the url property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the orgAttribute property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orgAttribute property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrgAttribute().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeBundleType }
     *
     *
     */
    public List<AttributeBundleType> getOrgAttribute() {
        if (orgAttribute == null) {
            orgAttribute = new ArrayList<AttributeBundleType>();
        }
        return this.orgAttribute;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="cv_id" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Institution {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "cv_id")
        protected Integer cvId;

        /**
         * Gets the value of the value property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the cvId property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public int getCvId() {
            if (cvId == null) {
                return  0;
            } else {
                return cvId;
            }
        }

        /**
         * Sets the value of the cvId property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setCvId(Integer value) {
            this.cvId = value;
        }

    }

}
