//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonnelType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PersonnelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Person" type="{}PersonType"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element name="PublicContact" type="{}ContactType"/>
 *             &lt;element name="PrivateContact" type="{}ContactType" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="PrivateContact" type="{}ContactType"/>
 *             &lt;element name="PublicContact" type="{}ContactType" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="Title" type="{}TitleList" minOccurs="0"/>
 *         &lt;element name="PersonRef" type="{}XrefType" minOccurs="0"/>
 *         &lt;element name="PersonPermissions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}CVIdentifiers"/>
 *       &lt;attribute name="PrimaryContact" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="IsDirector" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DisplayWeb" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Status" type="{}typeStatus" default="current" />
 *       &lt;attribute name="pubStat" type="{http://www.w3.org/2001/XMLSchema}string" default="3" />
 *       &lt;attribute name="cv_org_id" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonnelType", propOrder = {
    "content"
})
public class PersonnelType {

    @XmlElementRefs({
        @XmlElementRef(name = "PublicContact", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PersonRef", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PersonPermissions", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Person", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PrivateContact", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Title", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> content;
    @XmlAttribute(name = "PrimaryContact")
    protected Boolean primaryContact;
    @XmlAttribute(name = "IsDirector")
    protected Boolean isDirector;
    @XmlAttribute(name = "DisplayWeb", required = true)
    protected boolean displayWeb;
    @XmlAttribute(name = "Status")
    protected TypeStatus status;
    @XmlAttribute(name = "pubStat")
    protected String pubStat;
    @XmlAttribute(name = "cv_org_id")
    protected Integer cvOrgId;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;
    @XmlAttribute(name = "ncbi_id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ncbiId;

    /**
     * Gets the rest of the content model.
     *
     * <p>
     * You are getting this "catch-all" property because of the following reason:
     * The field name "PrivateContact" is used by two different parts of a schema. See:
     * line 1853 of file:/Users/whaleyr/box/Box%20Sync/PharmGKB/ClinVar/templates/clinvar_submission_1.5.xsd
     * line 1850 of file:/Users/whaleyr/box/Box%20Sync/PharmGKB/ClinVar/templates/clinvar_submission_1.5.xsd
     * <p>
     * To get rid of this property, apply a property customization to one
     * of both of the following declarations to change their names:
     * Gets the value of the content property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ContactType }{@code >}
     * {@link JAXBElement }{@code <}{@link XrefType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TitleList }{@code >}
     * {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     * {@link JAXBElement }{@code <}{@link ContactType }{@code >}
     *
     *
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

    /**
     * Gets the value of the primaryContact property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isPrimaryContact() {
        return primaryContact;
    }

    /**
     * Sets the value of the primaryContact property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setPrimaryContact(Boolean value) {
        this.primaryContact = value;
    }

    /**
     * Gets the value of the isDirector property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isIsDirector() {
        return isDirector;
    }

    /**
     * Sets the value of the isDirector property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setIsDirector(Boolean value) {
        this.isDirector = value;
    }

    /**
     * Gets the value of the displayWeb property.
     *
     */
    public boolean isDisplayWeb() {
        return displayWeb;
    }

    /**
     * Sets the value of the displayWeb property.
     *
     */
    public void setDisplayWeb(boolean value) {
        this.displayWeb = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return
     *     possible object is
     *     {@link TypeStatus }
     *
     */
    public TypeStatus getStatus() {
        if (status == null) {
            return TypeStatus.CURRENT;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *     allowed object is
     *     {@link TypeStatus }
     *
     */
    public void setStatus(TypeStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the pubStat property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPubStat() {
        if (pubStat == null) {
            return "3";
        } else {
            return pubStat;
        }
    }

    /**
     * Sets the value of the pubStat property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPubStat(String value) {
        this.pubStat = value;
    }

    /**
     * Gets the value of the cvOrgId property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public int getCvOrgId() {
        if (cvOrgId == null) {
            return  0;
        } else {
            return cvOrgId;
        }
    }

    /**
     * Sets the value of the cvOrgId property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setCvOrgId(Integer value) {
        this.cvOrgId = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the ncbiId property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getNcbiId() {
        return ncbiId;
    }

    /**
     * Sets the value of the ncbiId property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setNcbiId(BigInteger value) {
        this.ncbiId = value;
    }

}
