//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 *  The SubmissionSet is a set of asserted relationships. Within ClinVar
 *                 this may be the set of assertions that constitute the accession (prefix RCV)
 *                 assigned to independent assertions (accession prefix SCV). For testing laboratories,
 *                 this may be a test panel. If the set represents a reference accession (RCV) there
 *                 can be be only 1 for the SubmissionSet. If the Set is a test panel, the Set can
 *                 consist of any mixture of RCV and SCV assertions. If an SCV is known to be a member
 *                 of an RCV, only the RCV should be included in the submission. The set can also be
 *                 used to submit a set of assertions from a source that are not part of a single
 *                 accession, but a collection of SCV's from a laboratory.
 *
 * <p>Java class for SubmissionSetType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SubmissionSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="SubmitterOfRecord" type="{}SubmitterType"/>
 *           &lt;element name="SubmitterOfRecordID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="Submitter" type="{}OrgType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="OrgID" type="{}OrgIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RefTrait" type="{}TraitType" minOccurs="0"/>
 *         &lt;element name="ClinvarSubmission" type="{}SubmissionType" maxOccurs="unbounded"/>
 *         &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
 *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StudyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReleaseStatus" type="{}ReleaseStatusType" minOccurs="0"/>
 *         &lt;element name="StudyDescription" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}CVIdentifiers"/>
 *       &lt;attribute name="sub_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="set_key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmissionSetType", propOrder = {
    "submitterOfRecord",
    "submitterOfRecordID",
    "submitter",
    "orgID",
    "title",
    "refTrait",
    "clinvarSubmission",
    "comment",
    "citation",
    "xRef",
    "studyName",
    "releaseStatus",
    "studyDescription"
})
public class SubmissionSetType {

    @XmlElement(name = "SubmitterOfRecord")
    protected SubmitterType submitterOfRecord;
    @XmlElement(name = "SubmitterOfRecordID")
    protected Integer submitterOfRecordID;
    @XmlElement(name = "Submitter")
    protected List<OrgType> submitter;
    @XmlElement(name = "OrgID")
    protected List<OrgIDType> orgID;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "RefTrait")
    protected TraitType refTrait;
    @XmlElement(name = "ClinvarSubmission", required = true)
    protected List<SubmissionType> clinvarSubmission;
    @XmlElement(name = "Comment")
    protected CommentType comment;
    @XmlElement(name = "Citation")
    protected List<CitationType> citation;
    @XmlElement(name = "XRef")
    protected List<XrefType> xRef;
    @XmlElement(name = "StudyName")
    protected String studyName;
    @XmlElement(name = "ReleaseStatus", defaultValue = "public")
    @XmlSchemaType(name = "string")
    protected ReleaseStatusType releaseStatus;
    @XmlElement(name = "StudyDescription")
    protected List<String> studyDescription;
    @XmlAttribute(name = "sub_id")
    protected String subId;
    @XmlAttribute(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "set_key")
    protected String setKey;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;
    @XmlAttribute(name = "ncbi_id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ncbiId;

    /**
     * Gets the value of the submitterOfRecord property.
     *
     * @return
     *     possible object is
     *     {@link SubmitterType }
     *
     */
    public SubmitterType getSubmitterOfRecord() {
        return submitterOfRecord;
    }

    /**
     * Sets the value of the submitterOfRecord property.
     *
     * @param value
     *     allowed object is
     *     {@link SubmitterType }
     *
     */
    public void setSubmitterOfRecord(SubmitterType value) {
        this.submitterOfRecord = value;
    }

    /**
     * Gets the value of the submitterOfRecordID property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getSubmitterOfRecordID() {
        return submitterOfRecordID;
    }

    /**
     * Sets the value of the submitterOfRecordID property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setSubmitterOfRecordID(Integer value) {
        this.submitterOfRecordID = value;
    }

    /**
     * Gets the value of the submitter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the submitter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubmitter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrgType }
     *
     *
     */
    public List<OrgType> getSubmitter() {
        if (submitter == null) {
            submitter = new ArrayList<OrgType>();
        }
        return this.submitter;
    }

    /**
     * Gets the value of the orgID property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orgID property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrgID().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrgIDType }
     *
     *
     */
    public List<OrgIDType> getOrgID() {
        if (orgID == null) {
            orgID = new ArrayList<OrgIDType>();
        }
        return this.orgID;
    }

    /**
     * Gets the value of the title property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the refTrait property.
     *
     * @return
     *     possible object is
     *     {@link TraitType }
     *
     */
    public TraitType getRefTrait() {
        return refTrait;
    }

    /**
     * Sets the value of the refTrait property.
     *
     * @param value
     *     allowed object is
     *     {@link TraitType }
     *
     */
    public void setRefTrait(TraitType value) {
        this.refTrait = value;
    }

    /**
     * Gets the value of the clinvarSubmission property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clinvarSubmission property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClinvarSubmission().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubmissionType }
     *
     *
     */
    public List<SubmissionType> getClinvarSubmission() {
        if (clinvarSubmission == null) {
            clinvarSubmission = new ArrayList<SubmissionType>();
        }
        return this.clinvarSubmission;
    }

    /**
     * Gets the value of the comment property.
     *
     * @return
     *     possible object is
     *     {@link CommentType }
     *
     */
    public CommentType getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value
     *     allowed object is
     *     {@link CommentType }
     *
     */
    public void setComment(CommentType value) {
        this.comment = value;
    }

    /**
     * Gets the value of the citation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CitationType }
     *
     *
     */
    public List<CitationType> getCitation() {
        if (citation == null) {
            citation = new ArrayList<CitationType>();
        }
        return this.citation;
    }

    /**
     * Gets the value of the xRef property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xRef property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXRef().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XrefType }
     *
     *
     */
    public List<XrefType> getXRef() {
        if (xRef == null) {
            xRef = new ArrayList<XrefType>();
        }
        return this.xRef;
    }

    /**
     * Gets the value of the studyName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStudyName() {
        return studyName;
    }

    /**
     * Sets the value of the studyName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStudyName(String value) {
        this.studyName = value;
    }

    /**
     * Gets the value of the releaseStatus property.
     *
     * @return
     *     possible object is
     *     {@link ReleaseStatusType }
     *
     */
    public ReleaseStatusType getReleaseStatus() {
        return releaseStatus;
    }

    /**
     * Sets the value of the releaseStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link ReleaseStatusType }
     *
     */
    public void setReleaseStatus(ReleaseStatusType value) {
        this.releaseStatus = value;
    }

    /**
     * Gets the value of the studyDescription property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the studyDescription property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStudyDescription().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getStudyDescription() {
        if (studyDescription == null) {
            studyDescription = new ArrayList<String>();
        }
        return this.studyDescription;
    }

    /**
     * Gets the value of the subId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubId() {
        return subId;
    }

    /**
     * Sets the value of the subId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubId(String value) {
        this.subId = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the setKey property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSetKey() {
        return setKey;
    }

    /**
     * Sets the value of the setKey property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSetKey(String value) {
        this.setKey = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the ncbiId property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getNcbiId() {
        return ncbiId;
    }

    /**
     * Sets the value of the ncbiId property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setNcbiId(BigInteger value) {
        this.ncbiId = value;
    }

}
