//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for TraitType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TraitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TraitTypeElement">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>typeTraittypelist">
 *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Name" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Symbol" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AttributeSet" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TraitAttributeType">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;>typeTraitAttributetype">
 *                           &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Attribute" type="{}AttributeType"/>
 *                   &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TraitRelationship" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TraitRelationshipType">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;>typeTraitRelationshiptype">
 *                           &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Name" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Symbol" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="AttributeSet" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TraitRelationshipAttributeType">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;>typeTraitRelationshipAttributetype">
 *                                     &lt;attribute name="val_type" use="required" type="{}typeIdName" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Attribute" type="{}AttributeType"/>
 *                             &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{}CVIdentifiers"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}CVIdentifiers"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TraitType", propOrder = {
    "traitTypeElement",
    "name",
    "symbol",
    "attributeSet",
    "traitRelationship",
    "citation",
    "xRef",
    "comment"
})
public class TraitType {

    @XmlElement(name = "TraitTypeElement", required = true)
    protected TraitType.TraitTypeElement traitTypeElement;
    @XmlElement(name = "Name")
    protected List<SetElementSetType> name;
    @XmlElement(name = "Symbol")
    protected List<SetElementSetType> symbol;
    @XmlElement(name = "AttributeSet")
    protected List<TraitType.AttributeSet> attributeSet;
    @XmlElement(name = "TraitRelationship")
    protected List<TraitType.TraitRelationship> traitRelationship;
    @XmlElement(name = "Citation")
    protected List<CitationType> citation;
    @XmlElement(name = "XRef")
    protected List<XrefType> xRef;
    @XmlElement(name = "Comment")
    protected CommentType comment;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;
    @XmlAttribute(name = "ncbi_id")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ncbiId;

    /**
     * Gets the value of the traitTypeElement property.
     *
     * @return
     *     possible object is
     *     {@link TraitType.TraitTypeElement }
     *
     */
    public TraitType.TraitTypeElement getTraitTypeElement() {
        return traitTypeElement;
    }

    /**
     * Sets the value of the traitTypeElement property.
     *
     * @param value
     *     allowed object is
     *     {@link TraitType.TraitTypeElement }
     *
     */
    public void setTraitTypeElement(TraitType.TraitTypeElement value) {
        this.traitTypeElement = value;
    }

    /**
     * Gets the value of the name property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetElementSetType }
     *
     *
     */
    public List<SetElementSetType> getName() {
        if (name == null) {
            name = new ArrayList<SetElementSetType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the symbol property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the symbol property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSymbol().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetElementSetType }
     *
     *
     */
    public List<SetElementSetType> getSymbol() {
        if (symbol == null) {
            symbol = new ArrayList<SetElementSetType>();
        }
        return this.symbol;
    }

    /**
     * Gets the value of the attributeSet property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeSet property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeSet().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TraitType.AttributeSet }
     *
     *
     */
    public List<TraitType.AttributeSet> getAttributeSet() {
        if (attributeSet == null) {
            attributeSet = new ArrayList<TraitType.AttributeSet>();
        }
        return this.attributeSet;
    }

    /**
     * Gets the value of the traitRelationship property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the traitRelationship property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTraitRelationship().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TraitType.TraitRelationship }
     *
     *
     */
    public List<TraitType.TraitRelationship> getTraitRelationship() {
        if (traitRelationship == null) {
            traitRelationship = new ArrayList<TraitType.TraitRelationship>();
        }
        return this.traitRelationship;
    }

    /**
     * Gets the value of the citation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CitationType }
     *
     *
     */
    public List<CitationType> getCitation() {
        if (citation == null) {
            citation = new ArrayList<CitationType>();
        }
        return this.citation;
    }

    /**
     * Gets the value of the xRef property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xRef property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXRef().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XrefType }
     *
     *
     */
    public List<XrefType> getXRef() {
        if (xRef == null) {
            xRef = new ArrayList<XrefType>();
        }
        return this.xRef;
    }

    /**
     * Gets the value of the comment property.
     *
     * @return
     *     possible object is
     *     {@link CommentType }
     *
     */
    public CommentType getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value
     *     allowed object is
     *     {@link CommentType }
     *
     */
    public void setComment(CommentType value) {
        this.comment = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the ncbiId property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getNcbiId() {
        return ncbiId;
    }

    /**
     * Sets the value of the ncbiId property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setNcbiId(BigInteger value) {
        this.ncbiId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TraitAttributeType">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;>typeTraitAttributetype">
     *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Attribute" type="{}AttributeType"/>
     *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "traitAttributeType",
        "attribute",
        "citation",
        "xRef",
        "comment"
    })
    public static class AttributeSet {

        @XmlElement(name = "TraitAttributeType", required = true)
        protected TraitType.AttributeSet.TraitAttributeType traitAttributeType;
        @XmlElement(name = "Attribute", required = true)
        protected AttributeType attribute;
        @XmlElement(name = "Citation")
        protected List<CitationType> citation;
        @XmlElement(name = "XRef")
        protected List<XrefType> xRef;
        @XmlElement(name = "Comment")
        protected List<CommentType> comment;

        /**
         * Gets the value of the traitAttributeType property.
         *
         * @return
         *     possible object is
         *     {@link TraitType.AttributeSet.TraitAttributeType }
         *
         */
        public TraitType.AttributeSet.TraitAttributeType getTraitAttributeType() {
            return traitAttributeType;
        }

        /**
         * Sets the value of the traitAttributeType property.
         *
         * @param value
         *     allowed object is
         *     {@link TraitType.AttributeSet.TraitAttributeType }
         *
         */
        public void setTraitAttributeType(TraitType.AttributeSet.TraitAttributeType value) {
            this.traitAttributeType = value;
        }

        /**
         * Gets the value of the attribute property.
         *
         * @return
         *     possible object is
         *     {@link AttributeType }
         *
         */
        public AttributeType getAttribute() {
            return attribute;
        }

        /**
         * Sets the value of the attribute property.
         *
         * @param value
         *     allowed object is
         *     {@link AttributeType }
         *
         */
        public void setAttribute(AttributeType value) {
            this.attribute = value;
        }

        /**
         * Gets the value of the citation property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the citation property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCitation().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CitationType }
         *
         *
         */
        public List<CitationType> getCitation() {
            if (citation == null) {
                citation = new ArrayList<CitationType>();
            }
            return this.citation;
        }

        /**
         * Gets the value of the xRef property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the xRef property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getXRef().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XrefType }
         *
         *
         */
        public List<XrefType> getXRef() {
            if (xRef == null) {
                xRef = new ArrayList<XrefType>();
            }
            return this.xRef;
        }

        /**
         * Gets the value of the comment property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comment property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComment().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CommentType }
         *
         *
         */
        public List<CommentType> getComment() {
            if (comment == null) {
                comment = new ArrayList<CommentType>();
            }
            return this.comment;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;>typeTraitAttributetype">
         *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class TraitAttributeType {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "val_type", required = true)
            protected TypeIdName valType;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the valType property.
             *
             * @return
             *     possible object is
             *     {@link TypeIdName }
             *
             */
            public TypeIdName getValType() {
                return valType;
            }

            /**
             * Sets the value of the valType property.
             *
             * @param value
             *     allowed object is
             *     {@link TypeIdName }
             *
             */
            public void setValType(TypeIdName value) {
                this.valType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TraitRelationshipType">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;>typeTraitRelationshiptype">
     *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Name" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Symbol" type="{}SetElementSetType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="AttributeSet" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TraitRelationshipAttributeType">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;>typeTraitRelationshipAttributetype">
     *                           &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Attribute" type="{}AttributeType"/>
     *                   &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{}CVIdentifiers"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "traitRelationshipType",
        "name",
        "symbol",
        "attributeSet",
        "citation",
        "xRef",
        "comment"
    })
    public static class TraitRelationship {

        @XmlElement(name = "TraitRelationshipType", required = true)
        protected TraitType.TraitRelationship.TraitRelationshipType traitRelationshipType;
        @XmlElement(name = "Name")
        protected List<SetElementSetType> name;
        @XmlElement(name = "Symbol")
        protected List<SetElementSetType> symbol;
        @XmlElement(name = "AttributeSet")
        protected List<TraitType.TraitRelationship.AttributeSet> attributeSet;
        @XmlElement(name = "Citation")
        protected List<CitationType> citation;
        @XmlElement(name = "XRef")
        protected List<XrefType> xRef;
        @XmlElement(name = "Comment")
        protected CommentType comment;
        @XmlAttribute(name = "id")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger id;
        @XmlAttribute(name = "ncbi_id")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger ncbiId;

        /**
         * Gets the value of the traitRelationshipType property.
         *
         * @return
         *     possible object is
         *     {@link TraitType.TraitRelationship.TraitRelationshipType }
         *
         */
        public TraitType.TraitRelationship.TraitRelationshipType getTraitRelationshipType() {
            return traitRelationshipType;
        }

        /**
         * Sets the value of the traitRelationshipType property.
         *
         * @param value
         *     allowed object is
         *     {@link TraitType.TraitRelationship.TraitRelationshipType }
         *
         */
        public void setTraitRelationshipType(TraitType.TraitRelationship.TraitRelationshipType value) {
            this.traitRelationshipType = value;
        }

        /**
         * Gets the value of the name property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the name property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getName().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SetElementSetType }
         *
         *
         */
        public List<SetElementSetType> getName() {
            if (name == null) {
                name = new ArrayList<SetElementSetType>();
            }
            return this.name;
        }

        /**
         * Gets the value of the symbol property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the symbol property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSymbol().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SetElementSetType }
         *
         *
         */
        public List<SetElementSetType> getSymbol() {
            if (symbol == null) {
                symbol = new ArrayList<SetElementSetType>();
            }
            return this.symbol;
        }

        /**
         * Gets the value of the attributeSet property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attributeSet property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttributeSet().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TraitType.TraitRelationship.AttributeSet }
         *
         *
         */
        public List<TraitType.TraitRelationship.AttributeSet> getAttributeSet() {
            if (attributeSet == null) {
                attributeSet = new ArrayList<TraitType.TraitRelationship.AttributeSet>();
            }
            return this.attributeSet;
        }

        /**
         * Gets the value of the citation property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the citation property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCitation().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CitationType }
         *
         *
         */
        public List<CitationType> getCitation() {
            if (citation == null) {
                citation = new ArrayList<CitationType>();
            }
            return this.citation;
        }

        /**
         * Gets the value of the xRef property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the xRef property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getXRef().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XrefType }
         *
         *
         */
        public List<XrefType> getXRef() {
            if (xRef == null) {
                xRef = new ArrayList<XrefType>();
            }
            return this.xRef;
        }

        /**
         * Gets the value of the comment property.
         *
         * @return
         *     possible object is
         *     {@link CommentType }
         *
         */
        public CommentType getComment() {
            return comment;
        }

        /**
         * Sets the value of the comment property.
         *
         * @param value
         *     allowed object is
         *     {@link CommentType }
         *
         */
        public void setComment(CommentType value) {
            this.comment = value;
        }

        /**
         * Gets the value of the id property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setId(BigInteger value) {
            this.id = value;
        }

        /**
         * Gets the value of the ncbiId property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getNcbiId() {
            return ncbiId;
        }

        /**
         * Sets the value of the ncbiId property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setNcbiId(BigInteger value) {
            this.ncbiId = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TraitRelationshipAttributeType">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;>typeTraitRelationshipAttributetype">
         *                 &lt;attribute name="val_type" use="required" type="{}typeIdName" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Attribute" type="{}AttributeType"/>
         *         &lt;element name="Citation" type="{}CitationType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="XRef" type="{}XrefType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="Comment" type="{}CommentType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "traitRelationshipAttributeType",
            "attribute",
            "citation",
            "xRef",
            "comment"
        })
        public static class AttributeSet {

            @XmlElement(name = "TraitRelationshipAttributeType", required = true)
            protected TraitType.TraitRelationship.AttributeSet.TraitRelationshipAttributeType traitRelationshipAttributeType;
            @XmlElement(name = "Attribute", required = true)
            protected AttributeType attribute;
            @XmlElement(name = "Citation")
            protected List<CitationType> citation;
            @XmlElement(name = "XRef")
            protected List<XrefType> xRef;
            @XmlElement(name = "Comment")
            protected List<CommentType> comment;

            /**
             * Gets the value of the traitRelationshipAttributeType property.
             *
             * @return
             *     possible object is
             *     {@link TraitType.TraitRelationship.AttributeSet.TraitRelationshipAttributeType }
             *
             */
            public TraitType.TraitRelationship.AttributeSet.TraitRelationshipAttributeType getTraitRelationshipAttributeType() {
                return traitRelationshipAttributeType;
            }

            /**
             * Sets the value of the traitRelationshipAttributeType property.
             *
             * @param value
             *     allowed object is
             *     {@link TraitType.TraitRelationship.AttributeSet.TraitRelationshipAttributeType }
             *
             */
            public void setTraitRelationshipAttributeType(TraitType.TraitRelationship.AttributeSet.TraitRelationshipAttributeType value) {
                this.traitRelationshipAttributeType = value;
            }

            /**
             * Gets the value of the attribute property.
             *
             * @return
             *     possible object is
             *     {@link AttributeType }
             *
             */
            public AttributeType getAttribute() {
                return attribute;
            }

            /**
             * Sets the value of the attribute property.
             *
             * @param value
             *     allowed object is
             *     {@link AttributeType }
             *
             */
            public void setAttribute(AttributeType value) {
                this.attribute = value;
            }

            /**
             * Gets the value of the citation property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the citation property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCitation().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CitationType }
             *
             *
             */
            public List<CitationType> getCitation() {
                if (citation == null) {
                    citation = new ArrayList<CitationType>();
                }
                return this.citation;
            }

            /**
             * Gets the value of the xRef property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the xRef property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getXRef().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link XrefType }
             *
             *
             */
            public List<XrefType> getXRef() {
                if (xRef == null) {
                    xRef = new ArrayList<XrefType>();
                }
                return this.xRef;
            }

            /**
             * Gets the value of the comment property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the comment property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getComment().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CommentType }
             *
             *
             */
            public List<CommentType> getComment() {
                if (comment == null) {
                    comment = new ArrayList<CommentType>();
                }
                return this.comment;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;>typeTraitRelationshipAttributetype">
             *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class TraitRelationshipAttributeType {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "val_type", required = true)
                protected TypeIdName valType;

                /**
                 * Gets the value of the value property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the valType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link TypeIdName }
                 *
                 */
                public TypeIdName getValType() {
                    return valType;
                }

                /**
                 * Sets the value of the valType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link TypeIdName }
                 *
                 */
                public void setValType(TypeIdName value) {
                    this.valType = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;>typeTraitRelationshiptype">
         *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class TraitRelationshipType {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "val_type", required = true)
            protected TypeIdName valType;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the valType property.
             *
             * @return
             *     possible object is
             *     {@link TypeIdName }
             *
             */
            public TypeIdName getValType() {
                return valType;
            }

            /**
             * Sets the value of the valType property.
             *
             * @param value
             *     allowed object is
             *     {@link TypeIdName }
             *
             */
            public void setValType(TypeIdName value) {
                this.valType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>typeTraittypelist">
     *       &lt;attribute name="val_type" use="required" type="{}typeIdName" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TraitTypeElement {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "val_type", required = true)
        protected TypeIdName valType;

        /**
         * Gets the value of the value property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the valType property.
         *
         * @return
         *     possible object is
         *     {@link TypeIdName }
         *
         */
        public TypeIdName getValType() {
            return valType;
        }

        /**
         * Sets the value of the valType property.
         *
         * @param value
         *     allowed object is
         *     {@link TypeIdName }
         *
         */
        public void setValType(TypeIdName value) {
            this.valType = value;
        }

    }

}
