//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.10.16 at 09:04:14 AM PDT
//


package org.pharmgkb.io.exporter.clinvar.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * XRefs are used to represent references to data from external
 *                 databases. These are stored in the ClinVar database to represent objects like
 *                 GeneIDs in Gene or MIM numbers in OMIM, and are flexible enough to be used broadly.
 *                 The db is the database name used for the external reference (e.g. 'Gene' or 'OMIM')
 *                 and the ID is that database identifier (e.g. the GeneID or MIM number). The type is
 *                 optional and should be used if there are multiple types of identifiers from a
 *                 database. For example, from OMIM we may get both MIM numbers and identifiers for
 *                 allelic variants; those should be specified as the type for the XRef. Expect ID to
 *                 not be provided only if this is used for submitting a URL on it's own. XSD does not
 *                 permit choice for attributes so validation of these will need to be in another layer
 *                 (XSLT)
 *
 * <p>Java class for XrefType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XrefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="db" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="cv_id" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="Status" type="{}typeStatus" default="current" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XrefType")
public class XrefType {

    @XmlAttribute(name = "db", required = true)
    protected String db;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "URL")
    @XmlSchemaType(name = "anyURI")
    protected String url;
    @XmlAttribute(name = "cv_id")
    protected Integer cvId;
    @XmlAttribute(name = "Status")
    protected TypeStatus status;

    /**
     * Gets the value of the db property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDb() {
        return db;
    }

    /**
     * Sets the value of the db property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDb(String value) {
        this.db = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the url property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the cvId property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public int getCvId() {
        if (cvId == null) {
            return  0;
        } else {
            return cvId;
        }
    }

    /**
     * Sets the value of the cvId property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setCvId(Integer value) {
        this.cvId = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return
     *     possible object is
     *     {@link TypeStatus }
     *
     */
    public TypeStatus getStatus() {
        if (status == null) {
            return TypeStatus.CURRENT;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *     allowed object is
     *     {@link TypeStatus }
     *
     */
    public void setStatus(TypeStatus value) {
        this.status = value;
    }

}
